=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'cgi'

module TalonOne
  class ManagementApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Coupon Created Event
    # @param coupon_created_event_request [CouponCreatedEventRequest] ...
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def coupon_created_event(coupon_created_event_request, opts = {})
      coupon_created_event_with_http_info(coupon_created_event_request, opts)
      nil
    end

    # Coupon Created Event
    # @param coupon_created_event_request [CouponCreatedEventRequest] ...
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def coupon_created_event_with_http_info(coupon_created_event_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ManagementApi.coupon_created_event ...'
      end
      # verify the required parameter 'coupon_created_event_request' is set
      if @api_client.config.client_side_validation && coupon_created_event_request.nil?
        fail ArgumentError, "Missing the required parameter 'coupon_created_event_request' when calling ManagementApi.coupon_created_event"
      end
      # resource path
      local_var_path = '/CouponCreatedEvent'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(coupon_created_event_request)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['management_key', 'manager_auth', 'api_key_v1']

      new_options = opts.merge(
        :operation => :"ManagementApi.coupon_created_event",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ManagementApi#coupon_created_event\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Coupon Deleted Event
    # @param coupon_deleted_event_request [CouponDeletedEventRequest] ...
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def coupon_deleted_event(coupon_deleted_event_request, opts = {})
      coupon_deleted_event_with_http_info(coupon_deleted_event_request, opts)
      nil
    end

    # Coupon Deleted Event
    # @param coupon_deleted_event_request [CouponDeletedEventRequest] ...
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def coupon_deleted_event_with_http_info(coupon_deleted_event_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ManagementApi.coupon_deleted_event ...'
      end
      # verify the required parameter 'coupon_deleted_event_request' is set
      if @api_client.config.client_side_validation && coupon_deleted_event_request.nil?
        fail ArgumentError, "Missing the required parameter 'coupon_deleted_event_request' when calling ManagementApi.coupon_deleted_event"
      end
      # resource path
      local_var_path = '/CouponDeletedEvent'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(coupon_deleted_event_request)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['management_key', 'manager_auth', 'api_key_v1']

      new_options = opts.merge(
        :operation => :"ManagementApi.coupon_deleted_event",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ManagementApi#coupon_deleted_event\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Coupon Updated Event
    # @param coupon_updated_event_request [CouponUpdatedEventRequest] ...
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def coupon_updated_event(coupon_updated_event_request, opts = {})
      coupon_updated_event_with_http_info(coupon_updated_event_request, opts)
      nil
    end

    # Coupon Updated Event
    # @param coupon_updated_event_request [CouponUpdatedEventRequest] ...
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def coupon_updated_event_with_http_info(coupon_updated_event_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ManagementApi.coupon_updated_event ...'
      end
      # verify the required parameter 'coupon_updated_event_request' is set
      if @api_client.config.client_side_validation && coupon_updated_event_request.nil?
        fail ArgumentError, "Missing the required parameter 'coupon_updated_event_request' when calling ManagementApi.coupon_updated_event"
      end
      # resource path
      local_var_path = '/CouponUpdatedEvent'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(coupon_updated_event_request)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['management_key', 'manager_auth', 'api_key_v1']

      new_options = opts.merge(
        :operation => :"ManagementApi.coupon_updated_event",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ManagementApi#coupon_updated_event\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Changed Loyalty Points Event
    # @param loyalty_points_changed_event_request [LoyaltyPointsChangedEventRequest] ...
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def loyalty_points_changed_event(loyalty_points_changed_event_request, opts = {})
      loyalty_points_changed_event_with_http_info(loyalty_points_changed_event_request, opts)
      nil
    end

    # Changed Loyalty Points Event
    # @param loyalty_points_changed_event_request [LoyaltyPointsChangedEventRequest] ...
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def loyalty_points_changed_event_with_http_info(loyalty_points_changed_event_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ManagementApi.loyalty_points_changed_event ...'
      end
      # verify the required parameter 'loyalty_points_changed_event_request' is set
      if @api_client.config.client_side_validation && loyalty_points_changed_event_request.nil?
        fail ArgumentError, "Missing the required parameter 'loyalty_points_changed_event_request' when calling ManagementApi.loyalty_points_changed_event"
      end
      # resource path
      local_var_path = '/LoyaltyPointsChangedEvent'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(loyalty_points_changed_event_request)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['management_key', 'manager_auth', 'api_key_v1']

      new_options = opts.merge(
        :operation => :"ManagementApi.loyalty_points_changed_event",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ManagementApi#loyalty_points_changed_event\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Loyalty Tier Downgrade Event
    # @param loyalty_tier_downgrade_event_request [LoyaltyTierDowngradeEventRequest] ...
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def loyalty_tier_downgrade_event(loyalty_tier_downgrade_event_request, opts = {})
      loyalty_tier_downgrade_event_with_http_info(loyalty_tier_downgrade_event_request, opts)
      nil
    end

    # Loyalty Tier Downgrade Event
    # @param loyalty_tier_downgrade_event_request [LoyaltyTierDowngradeEventRequest] ...
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def loyalty_tier_downgrade_event_with_http_info(loyalty_tier_downgrade_event_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ManagementApi.loyalty_tier_downgrade_event ...'
      end
      # verify the required parameter 'loyalty_tier_downgrade_event_request' is set
      if @api_client.config.client_side_validation && loyalty_tier_downgrade_event_request.nil?
        fail ArgumentError, "Missing the required parameter 'loyalty_tier_downgrade_event_request' when calling ManagementApi.loyalty_tier_downgrade_event"
      end
      # resource path
      local_var_path = '/LoyaltyTierDowngradeEvent'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(loyalty_tier_downgrade_event_request)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['management_key', 'manager_auth', 'api_key_v1']

      new_options = opts.merge(
        :operation => :"ManagementApi.loyalty_tier_downgrade_event",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ManagementApi#loyalty_tier_downgrade_event\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # Loyalty Tier Upgrade Event
    # @param loyalty_tier_upgrade_event_request [LoyaltyTierUpgradeEventRequest] ...
    # @param [Hash] opts the optional parameters
    # @return [nil]
    def loyalty_tier_upgrade_event(loyalty_tier_upgrade_event_request, opts = {})
      loyalty_tier_upgrade_event_with_http_info(loyalty_tier_upgrade_event_request, opts)
      nil
    end

    # Loyalty Tier Upgrade Event
    # @param loyalty_tier_upgrade_event_request [LoyaltyTierUpgradeEventRequest] ...
    # @param [Hash] opts the optional parameters
    # @return [Array<(nil, Integer, Hash)>] nil, response status code and response headers
    def loyalty_tier_upgrade_event_with_http_info(loyalty_tier_upgrade_event_request, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: ManagementApi.loyalty_tier_upgrade_event ...'
      end
      # verify the required parameter 'loyalty_tier_upgrade_event_request' is set
      if @api_client.config.client_side_validation && loyalty_tier_upgrade_event_request.nil?
        fail ArgumentError, "Missing the required parameter 'loyalty_tier_upgrade_event_request' when calling ManagementApi.loyalty_tier_upgrade_event"
      end
      # resource path
      local_var_path = '/LoyaltyTierUpgradeEvent'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Content-Type'
      content_type = @api_client.select_header_content_type(['application/json'])
      if !content_type.nil?
          header_params['Content-Type'] = content_type
      end

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body] || @api_client.object_to_http_body(loyalty_tier_upgrade_event_request)

      # return_type
      return_type = opts[:debug_return_type]

      # auth_names
      auth_names = opts[:debug_auth_names] || ['management_key', 'manager_auth', 'api_key_v1']

      new_options = opts.merge(
        :operation => :"ManagementApi.loyalty_tier_upgrade_event",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:POST, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: ManagementApi#loyalty_tier_upgrade_event\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
