=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module TalonOne
  class AddedDeductedPointsNotification < ApiModelBase
    # The name of the employee who added or deducted points.
    attr_accessor :employee_name

    # The ID of the loyalty program.
    attr_accessor :loyalty_program_id

    # The type of notification.
    attr_accessor :notification_type

    # The integration ID of the customer profile to whom points were added or deducted.
    attr_accessor :profile_integration_id

    # The integration ID of the session through which the points were earned or lost.
    attr_accessor :session_integration_id

    # The ID of the subledger within the loyalty program where these points were added.
    attr_accessor :subledger_id

    # The notification source, that is, it indicates whether the points were added or deducted via one of the following routes:  - [The Campaign Manager](/docs/product/getting-started)  - [Management API](/management-api#tag/Loyalty)  - [Rule Engine](/docs/product/applications/evaluation-order-for-rules-and-filters) 
    attr_accessor :type_of_change

    # The ID of the employee who added or deducted points.
    attr_accessor :user_id

    # The amount of added or deducted loyalty points.
    attr_accessor :amount

    # The expiration date for loyalty points.
    attr_accessor :expiry_date

    # The action (addition or deduction) made with loyalty points.
    attr_accessor :operation

    # The reason for the points addition or deduction.
    attr_accessor :reason

    # The start date for loyalty points.
    attr_accessor :start_date

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'employee_name' => :'EmployeeName',
        :'loyalty_program_id' => :'LoyaltyProgramID',
        :'notification_type' => :'NotificationType',
        :'profile_integration_id' => :'ProfileIntegrationID',
        :'session_integration_id' => :'SessionIntegrationID',
        :'subledger_id' => :'SubledgerID',
        :'type_of_change' => :'TypeOfChange',
        :'user_id' => :'UserID',
        :'amount' => :'Amount',
        :'expiry_date' => :'ExpiryDate',
        :'operation' => :'Operation',
        :'reason' => :'Reason',
        :'start_date' => :'StartDate'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'employee_name' => :'String',
        :'loyalty_program_id' => :'Integer',
        :'notification_type' => :'String',
        :'profile_integration_id' => :'String',
        :'session_integration_id' => :'String',
        :'subledger_id' => :'String',
        :'type_of_change' => :'String',
        :'user_id' => :'Integer',
        :'amount' => :'Float',
        :'expiry_date' => :'Time',
        :'operation' => :'String',
        :'reason' => :'String',
        :'start_date' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::AddedDeductedPointsNotification` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::AddedDeductedPointsNotification`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'employee_name')
        self.employee_name = attributes[:'employee_name']
      else
        self.employee_name = nil
      end

      if attributes.key?(:'loyalty_program_id')
        self.loyalty_program_id = attributes[:'loyalty_program_id']
      else
        self.loyalty_program_id = nil
      end

      if attributes.key?(:'notification_type')
        self.notification_type = attributes[:'notification_type']
      else
        self.notification_type = nil
      end

      if attributes.key?(:'profile_integration_id')
        self.profile_integration_id = attributes[:'profile_integration_id']
      else
        self.profile_integration_id = nil
      end

      if attributes.key?(:'session_integration_id')
        self.session_integration_id = attributes[:'session_integration_id']
      else
        self.session_integration_id = nil
      end

      if attributes.key?(:'subledger_id')
        self.subledger_id = attributes[:'subledger_id']
      else
        self.subledger_id = nil
      end

      if attributes.key?(:'type_of_change')
        self.type_of_change = attributes[:'type_of_change']
      else
        self.type_of_change = nil
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      else
        self.user_id = nil
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      else
        self.amount = nil
      end

      if attributes.key?(:'expiry_date')
        self.expiry_date = attributes[:'expiry_date']
      end

      if attributes.key?(:'operation')
        self.operation = attributes[:'operation']
      else
        self.operation = nil
      end

      if attributes.key?(:'reason')
        self.reason = attributes[:'reason']
      else
        self.reason = nil
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @employee_name.nil?
        invalid_properties.push('invalid value for "employee_name", employee_name cannot be nil.')
      end

      if @loyalty_program_id.nil?
        invalid_properties.push('invalid value for "loyalty_program_id", loyalty_program_id cannot be nil.')
      end

      if @loyalty_program_id < 1
        invalid_properties.push('invalid value for "loyalty_program_id", must be greater than or equal to 1.')
      end

      if @notification_type.nil?
        invalid_properties.push('invalid value for "notification_type", notification_type cannot be nil.')
      end

      if @profile_integration_id.nil?
        invalid_properties.push('invalid value for "profile_integration_id", profile_integration_id cannot be nil.')
      end

      if @session_integration_id.nil?
        invalid_properties.push('invalid value for "session_integration_id", session_integration_id cannot be nil.')
      end

      if @subledger_id.nil?
        invalid_properties.push('invalid value for "subledger_id", subledger_id cannot be nil.')
      end

      if @type_of_change.nil?
        invalid_properties.push('invalid value for "type_of_change", type_of_change cannot be nil.')
      end

      if @user_id.nil?
        invalid_properties.push('invalid value for "user_id", user_id cannot be nil.')
      end

      if @amount.nil?
        invalid_properties.push('invalid value for "amount", amount cannot be nil.')
      end

      if @operation.nil?
        invalid_properties.push('invalid value for "operation", operation cannot be nil.')
      end

      if @reason.nil?
        invalid_properties.push('invalid value for "reason", reason cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @employee_name.nil?
      return false if @loyalty_program_id.nil?
      return false if @loyalty_program_id < 1
      return false if @notification_type.nil?
      notification_type_validator = EnumAttributeValidator.new('String', ["LoyaltyPointsDeducted", "LoyaltyPointsAdded"])
      return false unless notification_type_validator.valid?(@notification_type)
      return false if @profile_integration_id.nil?
      return false if @session_integration_id.nil?
      return false if @subledger_id.nil?
      return false if @type_of_change.nil?
      type_of_change_validator = EnumAttributeValidator.new('String', ["campaign_manager", "rule_engine", "management_api"])
      return false unless type_of_change_validator.valid?(@type_of_change)
      return false if @user_id.nil?
      return false if @amount.nil?
      return false if @operation.nil?
      operation_validator = EnumAttributeValidator.new('String', ["addition", "deduction"])
      return false unless operation_validator.valid?(@operation)
      return false if @reason.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] employee_name Value to be assigned
    def employee_name=(employee_name)
      if employee_name.nil?
        fail ArgumentError, 'employee_name cannot be nil'
      end

      @employee_name = employee_name
    end

    # Custom attribute writer method with validation
    # @param [Object] loyalty_program_id Value to be assigned
    def loyalty_program_id=(loyalty_program_id)
      if loyalty_program_id.nil?
        fail ArgumentError, 'loyalty_program_id cannot be nil'
      end

      if loyalty_program_id < 1
        fail ArgumentError, 'invalid value for "loyalty_program_id", must be greater than or equal to 1.'
      end

      @loyalty_program_id = loyalty_program_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] notification_type Object to be assigned
    def notification_type=(notification_type)
      validator = EnumAttributeValidator.new('String', ["LoyaltyPointsDeducted", "LoyaltyPointsAdded"])
      unless validator.valid?(notification_type)
        fail ArgumentError, "invalid value for \"notification_type\", must be one of #{validator.allowable_values}."
      end
      @notification_type = notification_type
    end

    # Custom attribute writer method with validation
    # @param [Object] profile_integration_id Value to be assigned
    def profile_integration_id=(profile_integration_id)
      if profile_integration_id.nil?
        fail ArgumentError, 'profile_integration_id cannot be nil'
      end

      @profile_integration_id = profile_integration_id
    end

    # Custom attribute writer method with validation
    # @param [Object] session_integration_id Value to be assigned
    def session_integration_id=(session_integration_id)
      if session_integration_id.nil?
        fail ArgumentError, 'session_integration_id cannot be nil'
      end

      @session_integration_id = session_integration_id
    end

    # Custom attribute writer method with validation
    # @param [Object] subledger_id Value to be assigned
    def subledger_id=(subledger_id)
      if subledger_id.nil?
        fail ArgumentError, 'subledger_id cannot be nil'
      end

      @subledger_id = subledger_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type_of_change Object to be assigned
    def type_of_change=(type_of_change)
      validator = EnumAttributeValidator.new('String', ["campaign_manager", "rule_engine", "management_api"])
      unless validator.valid?(type_of_change)
        fail ArgumentError, "invalid value for \"type_of_change\", must be one of #{validator.allowable_values}."
      end
      @type_of_change = type_of_change
    end

    # Custom attribute writer method with validation
    # @param [Object] user_id Value to be assigned
    def user_id=(user_id)
      if user_id.nil?
        fail ArgumentError, 'user_id cannot be nil'
      end

      @user_id = user_id
    end

    # Custom attribute writer method with validation
    # @param [Object] amount Value to be assigned
    def amount=(amount)
      if amount.nil?
        fail ArgumentError, 'amount cannot be nil'
      end

      @amount = amount
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] operation Object to be assigned
    def operation=(operation)
      validator = EnumAttributeValidator.new('String', ["addition", "deduction"])
      unless validator.valid?(operation)
        fail ArgumentError, "invalid value for \"operation\", must be one of #{validator.allowable_values}."
      end
      @operation = operation
    end

    # Custom attribute writer method with validation
    # @param [Object] reason Value to be assigned
    def reason=(reason)
      if reason.nil?
        fail ArgumentError, 'reason cannot be nil'
      end

      @reason = reason
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          employee_name == o.employee_name &&
          loyalty_program_id == o.loyalty_program_id &&
          notification_type == o.notification_type &&
          profile_integration_id == o.profile_integration_id &&
          session_integration_id == o.session_integration_id &&
          subledger_id == o.subledger_id &&
          type_of_change == o.type_of_change &&
          user_id == o.user_id &&
          amount == o.amount &&
          expiry_date == o.expiry_date &&
          operation == o.operation &&
          reason == o.reason &&
          start_date == o.start_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [employee_name, loyalty_program_id, notification_type, profile_integration_id, session_integration_id, subledger_id, type_of_change, user_id, amount, expiry_date, operation, reason, start_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
