=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module TalonOne
  class AwardLoyaltyPointsBlock < ApiModelBase
    # Unique identifier for this block.
    attr_accessor :id

    # Identifies the block variant and determines which additional properties are present in it.
    attr_accessor :type

    # Semantic labels attached to this block.
    attr_accessor :tags

    # The human-readable label attached to the awarded points.
    attr_accessor :name

    attr_accessor :program

    # The customer profile that receives the points. `Current` targets the customer in the current session; `Advocate` targets the person who invited their friend via referral program.
    attr_accessor :recipient

    # The name of the subledger to add points to. Can be empty if this block adds points to the loyalty program's main ledger instead of a subledger.
    attr_accessor :subledger

    attr_accessor :target

    attr_accessor :value

    # When `true`, applies a partial points reward when the requested value exceeds the configured budget.
    attr_accessor :partial

    # When `true`, the awarded points require manual or delayed activation before becoming active. Mutually exclusive with `startDate`.
    attr_accessor :awaits_activation

    # Timestamp at which the awarded points become active. Mutually exclusive with `awaitsActivation`.
    attr_accessor :start_date

    # Relative duration (e.g. `30D`) after which the awarded points expire. Mutually exclusive with `expiryDate`.
    attr_accessor :validity_duration

    # Timestamp at which the awarded points expire. Mutually exclusive with `validityDuration`.
    attr_accessor :expiry_date

    # Relative duration (e.g. `3D`) the awarded points remain pending before activation.
    attr_accessor :pending_duration

    # Promotion blocks evaluated when this block fails or returns false.
    attr_accessor :on_failure

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'type' => :'type',
        :'tags' => :'tags',
        :'name' => :'name',
        :'program' => :'program',
        :'recipient' => :'recipient',
        :'subledger' => :'subledger',
        :'target' => :'target',
        :'value' => :'value',
        :'partial' => :'partial',
        :'awaits_activation' => :'awaitsActivation',
        :'start_date' => :'startDate',
        :'validity_duration' => :'validityDuration',
        :'expiry_date' => :'expiryDate',
        :'pending_duration' => :'pendingDuration',
        :'on_failure' => :'onFailure'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'type' => :'String',
        :'tags' => :'Array<String>',
        :'name' => :'String',
        :'program' => :'AwardLoyaltyPointsBlock1Program',
        :'recipient' => :'String',
        :'subledger' => :'String',
        :'target' => :'AwardLoyaltyPointsTarget',
        :'value' => :'AwardLoyaltyPointsBlock1Value',
        :'partial' => :'Boolean',
        :'awaits_activation' => :'Boolean',
        :'start_date' => :'Object',
        :'validity_duration' => :'String',
        :'expiry_date' => :'Object',
        :'pending_duration' => :'String',
        :'on_failure' => :'Array<Block>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'start_date',
        :'expiry_date',
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'BaseBlock'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::AwardLoyaltyPointsBlock` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::AwardLoyaltyPointsBlock`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'tags')
        if (value = attributes[:'tags']).is_a?(Array)
          self.tags = value
        end
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'program')
        self.program = attributes[:'program']
      else
        self.program = nil
      end

      if attributes.key?(:'recipient')
        self.recipient = attributes[:'recipient']
      else
        self.recipient = nil
      end

      if attributes.key?(:'subledger')
        self.subledger = attributes[:'subledger']
      else
        self.subledger = nil
      end

      if attributes.key?(:'target')
        self.target = attributes[:'target']
      else
        self.target = nil
      end

      if attributes.key?(:'value')
        self.value = attributes[:'value']
      else
        self.value = nil
      end

      if attributes.key?(:'partial')
        self.partial = attributes[:'partial']
      end

      if attributes.key?(:'awaits_activation')
        self.awaits_activation = attributes[:'awaits_activation']
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      end

      if attributes.key?(:'validity_duration')
        self.validity_duration = attributes[:'validity_duration']
      end

      if attributes.key?(:'expiry_date')
        self.expiry_date = attributes[:'expiry_date']
      end

      if attributes.key?(:'pending_duration')
        self.pending_duration = attributes[:'pending_duration']
      end

      if attributes.key?(:'on_failure')
        if (value = attributes[:'on_failure']).is_a?(Array)
          self.on_failure = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @program.nil?
        invalid_properties.push('invalid value for "program", program cannot be nil.')
      end

      if @recipient.nil?
        invalid_properties.push('invalid value for "recipient", recipient cannot be nil.')
      end

      if @subledger.nil?
        invalid_properties.push('invalid value for "subledger", subledger cannot be nil.')
      end

      if @target.nil?
        invalid_properties.push('invalid value for "target", target cannot be nil.')
      end

      if @value.nil?
        invalid_properties.push('invalid value for "value", value cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @type.nil?
      return false if @name.nil?
      return false if @program.nil?
      return false if @recipient.nil?
      recipient_validator = EnumAttributeValidator.new('String', ["Current", "Advocate"])
      return false unless recipient_validator.valid?(@recipient)
      return false if @subledger.nil?
      return false if @target.nil?
      return false if @value.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] type Value to be assigned
    def type=(type)
      if type.nil?
        fail ArgumentError, 'type cannot be nil'
      end

      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] program Value to be assigned
    def program=(program)
      if program.nil?
        fail ArgumentError, 'program cannot be nil'
      end

      @program = program
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] recipient Object to be assigned
    def recipient=(recipient)
      validator = EnumAttributeValidator.new('String', ["Current", "Advocate"])
      unless validator.valid?(recipient)
        fail ArgumentError, "invalid value for \"recipient\", must be one of #{validator.allowable_values}."
      end
      @recipient = recipient
    end

    # Custom attribute writer method with validation
    # @param [Object] subledger Value to be assigned
    def subledger=(subledger)
      if subledger.nil?
        fail ArgumentError, 'subledger cannot be nil'
      end

      @subledger = subledger
    end

    # Custom attribute writer method with validation
    # @param [Object] target Value to be assigned
    def target=(target)
      if target.nil?
        fail ArgumentError, 'target cannot be nil'
      end

      @target = target
    end

    # Custom attribute writer method with validation
    # @param [Object] value Value to be assigned
    def value=(value)
      if value.nil?
        fail ArgumentError, 'value cannot be nil'
      end

      @value = value
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          type == o.type &&
          tags == o.tags &&
          name == o.name &&
          program == o.program &&
          recipient == o.recipient &&
          subledger == o.subledger &&
          target == o.target &&
          value == o.value &&
          partial == o.partial &&
          awaits_activation == o.awaits_activation &&
          start_date == o.start_date &&
          validity_duration == o.validity_duration &&
          expiry_date == o.expiry_date &&
          pending_duration == o.pending_duration &&
          on_failure == o.on_failure
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, type, tags, name, program, recipient, subledger, target, value, partial, awaits_activation, start_date, validity_duration, expiry_date, pending_duration, on_failure].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
