=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module TalonOne
  # Properties returned when a rule triggers a `boostLoyaltyTier` effect. The customer is temporarily placed in a higher loyalty tier for a specified period without any change to their points balance. 
  class BoostLoyaltyTierEffectProps < ApiModelBase
    # The ID of the loyalty program.
    attr_accessor :program_id

    # The ID of the subledger within the loyalty program.
    attr_accessor :sub_ledger_id

    # The name of the tier to which the customer is temporarily boosted.
    attr_accessor :tier_name

    # A reason for the tier boost.
    attr_accessor :reason

    # The date when the tier boost expires.
    attr_accessor :expiry_date

    # The unique identifier of the tier boost. Used to match the boost to its rollback effect when a session is cancelled.
    attr_accessor :boost_uuid

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'program_id' => :'programId',
        :'sub_ledger_id' => :'subLedgerId',
        :'tier_name' => :'tierName',
        :'reason' => :'reason',
        :'expiry_date' => :'expiryDate',
        :'boost_uuid' => :'boostUuid'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'program_id' => :'Integer',
        :'sub_ledger_id' => :'String',
        :'tier_name' => :'String',
        :'reason' => :'String',
        :'expiry_date' => :'Time',
        :'boost_uuid' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::BoostLoyaltyTierEffectProps` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::BoostLoyaltyTierEffectProps`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'program_id')
        self.program_id = attributes[:'program_id']
      else
        self.program_id = nil
      end

      if attributes.key?(:'sub_ledger_id')
        self.sub_ledger_id = attributes[:'sub_ledger_id']
      else
        self.sub_ledger_id = nil
      end

      if attributes.key?(:'tier_name')
        self.tier_name = attributes[:'tier_name']
      else
        self.tier_name = nil
      end

      if attributes.key?(:'reason')
        self.reason = attributes[:'reason']
      end

      if attributes.key?(:'expiry_date')
        self.expiry_date = attributes[:'expiry_date']
      else
        self.expiry_date = nil
      end

      if attributes.key?(:'boost_uuid')
        self.boost_uuid = attributes[:'boost_uuid']
      else
        self.boost_uuid = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @program_id.nil?
        invalid_properties.push('invalid value for "program_id", program_id cannot be nil.')
      end

      if @sub_ledger_id.nil?
        invalid_properties.push('invalid value for "sub_ledger_id", sub_ledger_id cannot be nil.')
      end

      if @tier_name.nil?
        invalid_properties.push('invalid value for "tier_name", tier_name cannot be nil.')
      end

      if @expiry_date.nil?
        invalid_properties.push('invalid value for "expiry_date", expiry_date cannot be nil.')
      end

      if @boost_uuid.nil?
        invalid_properties.push('invalid value for "boost_uuid", boost_uuid cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @program_id.nil?
      return false if @sub_ledger_id.nil?
      return false if @tier_name.nil?
      return false if @expiry_date.nil?
      return false if @boost_uuid.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] program_id Value to be assigned
    def program_id=(program_id)
      if program_id.nil?
        fail ArgumentError, 'program_id cannot be nil'
      end

      @program_id = program_id
    end

    # Custom attribute writer method with validation
    # @param [Object] sub_ledger_id Value to be assigned
    def sub_ledger_id=(sub_ledger_id)
      if sub_ledger_id.nil?
        fail ArgumentError, 'sub_ledger_id cannot be nil'
      end

      @sub_ledger_id = sub_ledger_id
    end

    # Custom attribute writer method with validation
    # @param [Object] tier_name Value to be assigned
    def tier_name=(tier_name)
      if tier_name.nil?
        fail ArgumentError, 'tier_name cannot be nil'
      end

      @tier_name = tier_name
    end

    # Custom attribute writer method with validation
    # @param [Object] expiry_date Value to be assigned
    def expiry_date=(expiry_date)
      if expiry_date.nil?
        fail ArgumentError, 'expiry_date cannot be nil'
      end

      @expiry_date = expiry_date
    end

    # Custom attribute writer method with validation
    # @param [Object] boost_uuid Value to be assigned
    def boost_uuid=(boost_uuid)
      if boost_uuid.nil?
        fail ArgumentError, 'boost_uuid cannot be nil'
      end

      @boost_uuid = boost_uuid
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          program_id == o.program_id &&
          sub_ledger_id == o.sub_ledger_id &&
          tier_name == o.tier_name &&
          reason == o.reason &&
          expiry_date == o.expiry_date &&
          boost_uuid == o.boost_uuid
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [program_id, sub_ledger_id, tier_name, reason, expiry_date, boost_uuid].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
