=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module TalonOne
  class CampaignSetBranchNode < ApiModelBase
    # Indicates the node type.
    attr_accessor :type

    # Name of the set.
    attr_accessor :name

    # An indicator of how the set operates on its elements.
    attr_accessor :operator

    # Child elements of this set.
    attr_accessor :elements

    # The ID of the campaign set.
    attr_accessor :group_id

    # An indicator of whether the campaign set is locked for modification.
    attr_accessor :locked

    # A description of the campaign set.
    attr_accessor :description

    # The mode by which campaigns in the campaign evaluation group are evaluated.
    attr_accessor :evaluation_mode

    # The evaluation scope of the campaign evaluation group.
    attr_accessor :evaluation_scope

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'name' => :'name',
        :'operator' => :'operator',
        :'elements' => :'elements',
        :'group_id' => :'groupId',
        :'locked' => :'locked',
        :'description' => :'description',
        :'evaluation_mode' => :'evaluationMode',
        :'evaluation_scope' => :'evaluationScope'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'String',
        :'name' => :'String',
        :'operator' => :'String',
        :'elements' => :'Array<CampaignSetNode>',
        :'group_id' => :'Integer',
        :'locked' => :'Boolean',
        :'description' => :'String',
        :'evaluation_mode' => :'String',
        :'evaluation_scope' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::CampaignSetBranchNode` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::CampaignSetBranchNode`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'operator')
        self.operator = attributes[:'operator']
      else
        self.operator = nil
      end

      if attributes.key?(:'elements')
        if (value = attributes[:'elements']).is_a?(Array)
          self.elements = value
        end
      else
        self.elements = nil
      end

      if attributes.key?(:'group_id')
        self.group_id = attributes[:'group_id']
      else
        self.group_id = nil
      end

      if attributes.key?(:'locked')
        self.locked = attributes[:'locked']
      else
        self.locked = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'evaluation_mode')
        self.evaluation_mode = attributes[:'evaluation_mode']
      else
        self.evaluation_mode = nil
      end

      if attributes.key?(:'evaluation_scope')
        self.evaluation_scope = attributes[:'evaluation_scope']
      else
        self.evaluation_scope = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      if @operator.nil?
        invalid_properties.push('invalid value for "operator", operator cannot be nil.')
      end

      if @elements.nil?
        invalid_properties.push('invalid value for "elements", elements cannot be nil.')
      end

      if @group_id.nil?
        invalid_properties.push('invalid value for "group_id", group_id cannot be nil.')
      end

      if @locked.nil?
        invalid_properties.push('invalid value for "locked", locked cannot be nil.')
      end

      if @evaluation_mode.nil?
        invalid_properties.push('invalid value for "evaluation_mode", evaluation_mode cannot be nil.')
      end

      if @evaluation_scope.nil?
        invalid_properties.push('invalid value for "evaluation_scope", evaluation_scope cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["SET"])
      return false unless type_validator.valid?(@type)
      return false if @name.nil?
      return false if @operator.nil?
      operator_validator = EnumAttributeValidator.new('String', ["ALL", "FIRST"])
      return false unless operator_validator.valid?(@operator)
      return false if @elements.nil?
      return false if @group_id.nil?
      return false if @locked.nil?
      return false if @evaluation_mode.nil?
      evaluation_mode_validator = EnumAttributeValidator.new('String', ["stackable", "listOrder", "lowestDiscount", "highestDiscount"])
      return false unless evaluation_mode_validator.valid?(@evaluation_mode)
      return false if @evaluation_scope.nil?
      evaluation_scope_validator = EnumAttributeValidator.new('String', ["cartItem", "session"])
      return false unless evaluation_scope_validator.valid?(@evaluation_scope)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["SET"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      @name = name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] operator Object to be assigned
    def operator=(operator)
      validator = EnumAttributeValidator.new('String', ["ALL", "FIRST"])
      unless validator.valid?(operator)
        fail ArgumentError, "invalid value for \"operator\", must be one of #{validator.allowable_values}."
      end
      @operator = operator
    end

    # Custom attribute writer method with validation
    # @param [Object] elements Value to be assigned
    def elements=(elements)
      if elements.nil?
        fail ArgumentError, 'elements cannot be nil'
      end

      @elements = elements
    end

    # Custom attribute writer method with validation
    # @param [Object] group_id Value to be assigned
    def group_id=(group_id)
      if group_id.nil?
        fail ArgumentError, 'group_id cannot be nil'
      end

      @group_id = group_id
    end

    # Custom attribute writer method with validation
    # @param [Object] locked Value to be assigned
    def locked=(locked)
      if locked.nil?
        fail ArgumentError, 'locked cannot be nil'
      end

      @locked = locked
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] evaluation_mode Object to be assigned
    def evaluation_mode=(evaluation_mode)
      validator = EnumAttributeValidator.new('String', ["stackable", "listOrder", "lowestDiscount", "highestDiscount"])
      unless validator.valid?(evaluation_mode)
        fail ArgumentError, "invalid value for \"evaluation_mode\", must be one of #{validator.allowable_values}."
      end
      @evaluation_mode = evaluation_mode
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] evaluation_scope Object to be assigned
    def evaluation_scope=(evaluation_scope)
      validator = EnumAttributeValidator.new('String', ["cartItem", "session"])
      unless validator.valid?(evaluation_scope)
        fail ArgumentError, "invalid value for \"evaluation_scope\", must be one of #{validator.allowable_values}."
      end
      @evaluation_scope = evaluation_scope
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          name == o.name &&
          operator == o.operator &&
          elements == o.elements &&
          group_id == o.group_id &&
          locked == o.locked &&
          description == o.description &&
          evaluation_mode == o.evaluation_mode &&
          evaluation_scope == o.evaluation_scope
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, name, operator, elements, group_id, locked, description, evaluation_mode, evaluation_scope].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
