=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module TalonOne
  class CampaignCreatedNotificationItem < ApiModelBase
    # The type of the event. Can be one of the following: ['campaign_state_changed', 'campaign_ruleset_changed', 'campaign_edited', 'campaign_created', 'campaign_deleted'] 
    attr_accessor :event

    # The campaign whose state changed.
    attr_accessor :campaign

    # The current ruleset.
    attr_accessor :ruleset

    # The current details of the [placeholders](https://docs.talon.one/docs/product/campaigns/templates/create-templates#use-placeholders) in the campaign.
    attr_accessor :placeholders

    # The campaign position within the evaluation tree.
    attr_accessor :evaluation_position

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'event' => :'Event',
        :'campaign' => :'campaign',
        :'ruleset' => :'ruleset',
        :'placeholders' => :'placeholders',
        :'evaluation_position' => :'evaluationPosition'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'event' => :'String',
        :'campaign' => :'Campaign',
        :'ruleset' => :'Ruleset',
        :'placeholders' => :'Array<PlaceholderDetails>',
        :'evaluation_position' => :'CampaignEvaluationPosition'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'CampaignNotificationItemBase'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::CampaignCreatedNotificationItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::CampaignCreatedNotificationItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'event')
        self.event = attributes[:'event']
      else
        self.event = nil
      end

      if attributes.key?(:'campaign')
        self.campaign = attributes[:'campaign']
      else
        self.campaign = nil
      end

      if attributes.key?(:'ruleset')
        self.ruleset = attributes[:'ruleset']
      end

      if attributes.key?(:'placeholders')
        if (value = attributes[:'placeholders']).is_a?(Array)
          self.placeholders = value
        end
      end

      if attributes.key?(:'evaluation_position')
        self.evaluation_position = attributes[:'evaluation_position']
      else
        self.evaluation_position = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @event.nil?
        invalid_properties.push('invalid value for "event", event cannot be nil.')
      end

      if @campaign.nil?
        invalid_properties.push('invalid value for "campaign", campaign cannot be nil.')
      end

      if @evaluation_position.nil?
        invalid_properties.push('invalid value for "evaluation_position", evaluation_position cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @event.nil?
      return false if @campaign.nil?
      return false if @evaluation_position.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] event Value to be assigned
    def event=(event)
      if event.nil?
        fail ArgumentError, 'event cannot be nil'
      end

      @event = event
    end

    # Custom attribute writer method with validation
    # @param [Object] campaign Value to be assigned
    def campaign=(campaign)
      if campaign.nil?
        fail ArgumentError, 'campaign cannot be nil'
      end

      @campaign = campaign
    end

    # Custom attribute writer method with validation
    # @param [Object] evaluation_position Value to be assigned
    def evaluation_position=(evaluation_position)
      if evaluation_position.nil?
        fail ArgumentError, 'evaluation_position cannot be nil'
      end

      @evaluation_position = evaluation_position
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          event == o.event &&
          campaign == o.campaign &&
          ruleset == o.ruleset &&
          placeholders == o.placeholders &&
          evaluation_position == o.evaluation_position
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [event, campaign, ruleset, placeholders, evaluation_position].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
