=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module TalonOne
  class CouponsNotificationData < ApiModelBase
    # The type of change that occurred.
    attr_accessor :type_of_change

    # The operation performed.
    attr_accessor :operation

    # The name of the employee associated with the operation.
    attr_accessor :employee_name

    # A list of extended coupon data.
    attr_accessor :data

    attr_accessor :total_result_size

    # The type of the notification
    attr_accessor :notification_type

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type_of_change' => :'TypeOfChange',
        :'operation' => :'Operation',
        :'employee_name' => :'EmployeeName',
        :'data' => :'data',
        :'total_result_size' => :'totalResultSize',
        :'notification_type' => :'NotificationType'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type_of_change' => :'String',
        :'operation' => :'String',
        :'employee_name' => :'String',
        :'data' => :'Array<ExtendedCoupon>',
        :'total_result_size' => :'Integer',
        :'notification_type' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::CouponsNotificationData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::CouponsNotificationData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type_of_change')
        self.type_of_change = attributes[:'type_of_change']
      else
        self.type_of_change = nil
      end

      if attributes.key?(:'operation')
        self.operation = attributes[:'operation']
      else
        self.operation = nil
      end

      if attributes.key?(:'employee_name')
        self.employee_name = attributes[:'employee_name']
      else
        self.employee_name = nil
      end

      if attributes.key?(:'data')
        if (value = attributes[:'data']).is_a?(Array)
          self.data = value
        end
      end

      if attributes.key?(:'total_result_size')
        self.total_result_size = attributes[:'total_result_size']
      end

      if attributes.key?(:'notification_type')
        self.notification_type = attributes[:'notification_type']
      else
        self.notification_type = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @type_of_change.nil?
        invalid_properties.push('invalid value for "type_of_change", type_of_change cannot be nil.')
      end

      if @operation.nil?
        invalid_properties.push('invalid value for "operation", operation cannot be nil.')
      end

      if @employee_name.nil?
        invalid_properties.push('invalid value for "employee_name", employee_name cannot be nil.')
      end

      if @notification_type.nil?
        invalid_properties.push('invalid value for "notification_type", notification_type cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @type_of_change.nil?
      return false if @operation.nil?
      return false if @employee_name.nil?
      return false if @notification_type.nil?
      notification_type_validator = EnumAttributeValidator.new('String', ["CouponUpdated", "CouponDeleted"])
      return false unless notification_type_validator.valid?(@notification_type)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] type_of_change Value to be assigned
    def type_of_change=(type_of_change)
      if type_of_change.nil?
        fail ArgumentError, 'type_of_change cannot be nil'
      end

      @type_of_change = type_of_change
    end

    # Custom attribute writer method with validation
    # @param [Object] operation Value to be assigned
    def operation=(operation)
      if operation.nil?
        fail ArgumentError, 'operation cannot be nil'
      end

      @operation = operation
    end

    # Custom attribute writer method with validation
    # @param [Object] employee_name Value to be assigned
    def employee_name=(employee_name)
      if employee_name.nil?
        fail ArgumentError, 'employee_name cannot be nil'
      end

      @employee_name = employee_name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] notification_type Object to be assigned
    def notification_type=(notification_type)
      validator = EnumAttributeValidator.new('String', ["CouponUpdated", "CouponDeleted"])
      unless validator.valid?(notification_type)
        fail ArgumentError, "invalid value for \"notification_type\", must be one of #{validator.allowable_values}."
      end
      @notification_type = notification_type
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type_of_change == o.type_of_change &&
          operation == o.operation &&
          employee_name == o.employee_name &&
          data == o.data &&
          total_result_size == o.total_result_size &&
          notification_type == o.notification_type
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type_of_change, operation, employee_name, data, total_result_size, notification_type].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
