=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module TalonOne
  # A reward instance held by a customer profile.
  class CustomerProfileReward < ApiModelBase
    # The ID of the customer reward instance. A customer profile can have multiple instances of the same reward.
    attr_accessor :id

    # The ID of the reward this instance belongs to.
    attr_accessor :reward_id

    # The name of the reward.
    attr_accessor :reward_name

    # The status of the customer reward: - `unlocked`: The reward is available for use. - `used`: The reward has been used. 
    attr_accessor :status

    # The date and time when the reward was unlocked.
    attr_accessor :unlocked_at

    # The integration ID of the customer profile that unlocked the reward.   For rewards unlocked with a loyalty card, this can be any customer profile  linked to that loyalty card. 
    attr_accessor :unlocked_by_integration_id

    # The date and time when the reward was used.
    attr_accessor :used_at

    # The integration ID of the customer profile that used the reward.   For rewards unlocked with a loyalty card, this can be any customer profile  linked to that loyalty card.   Only returned when the reward has been used. 
    attr_accessor :used_by_integration_id

    # The ID of the loyalty program that the loyalty card belongs to. Only returned for rewards unlocked with a loyalty card.
    attr_accessor :loyalty_program_id

    # The identifier of the loyalty card that the reward was unlocked with. Only returned for rewards unlocked with a loyalty card.
    attr_accessor :loyalty_card_identifier

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'reward_id' => :'rewardId',
        :'reward_name' => :'rewardName',
        :'status' => :'status',
        :'unlocked_at' => :'unlockedAt',
        :'unlocked_by_integration_id' => :'unlockedByIntegrationId',
        :'used_at' => :'usedAt',
        :'used_by_integration_id' => :'usedByIntegrationId',
        :'loyalty_program_id' => :'loyaltyProgramId',
        :'loyalty_card_identifier' => :'loyaltyCardIdentifier'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'reward_id' => :'Integer',
        :'reward_name' => :'String',
        :'status' => :'String',
        :'unlocked_at' => :'Time',
        :'unlocked_by_integration_id' => :'String',
        :'used_at' => :'Time',
        :'used_by_integration_id' => :'String',
        :'loyalty_program_id' => :'Integer',
        :'loyalty_card_identifier' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::CustomerProfileReward` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::CustomerProfileReward`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'reward_id')
        self.reward_id = attributes[:'reward_id']
      else
        self.reward_id = nil
      end

      if attributes.key?(:'reward_name')
        self.reward_name = attributes[:'reward_name']
      else
        self.reward_name = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'unlocked_at')
        self.unlocked_at = attributes[:'unlocked_at']
      else
        self.unlocked_at = nil
      end

      if attributes.key?(:'unlocked_by_integration_id')
        self.unlocked_by_integration_id = attributes[:'unlocked_by_integration_id']
      end

      if attributes.key?(:'used_at')
        self.used_at = attributes[:'used_at']
      end

      if attributes.key?(:'used_by_integration_id')
        self.used_by_integration_id = attributes[:'used_by_integration_id']
      end

      if attributes.key?(:'loyalty_program_id')
        self.loyalty_program_id = attributes[:'loyalty_program_id']
      end

      if attributes.key?(:'loyalty_card_identifier')
        self.loyalty_card_identifier = attributes[:'loyalty_card_identifier']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @reward_id.nil?
        invalid_properties.push('invalid value for "reward_id", reward_id cannot be nil.')
      end

      if @reward_name.nil?
        invalid_properties.push('invalid value for "reward_name", reward_name cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @unlocked_at.nil?
        invalid_properties.push('invalid value for "unlocked_at", unlocked_at cannot be nil.')
      end

      if !@loyalty_card_identifier.nil? && @loyalty_card_identifier.to_s.length > 108
        invalid_properties.push('invalid value for "loyalty_card_identifier", the character length must be smaller than or equal to 108.')
      end

      if !@loyalty_card_identifier.nil? && @loyalty_card_identifier.to_s.length < 4
        invalid_properties.push('invalid value for "loyalty_card_identifier", the character length must be greater than or equal to 4.')
      end

      pattern = Regexp.new(/^[A-Za-z0-9._%+@-]+$/)
      if !@loyalty_card_identifier.nil? && @loyalty_card_identifier !~ pattern
        invalid_properties.push("invalid value for \"loyalty_card_identifier\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @reward_id.nil?
      return false if @reward_name.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["unlocked", "used"])
      return false unless status_validator.valid?(@status)
      return false if @unlocked_at.nil?
      return false if !@loyalty_card_identifier.nil? && @loyalty_card_identifier.to_s.length > 108
      return false if !@loyalty_card_identifier.nil? && @loyalty_card_identifier.to_s.length < 4
      return false if !@loyalty_card_identifier.nil? && @loyalty_card_identifier !~ Regexp.new(/^[A-Za-z0-9._%+@-]+$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] reward_id Value to be assigned
    def reward_id=(reward_id)
      if reward_id.nil?
        fail ArgumentError, 'reward_id cannot be nil'
      end

      @reward_id = reward_id
    end

    # Custom attribute writer method with validation
    # @param [Object] reward_name Value to be assigned
    def reward_name=(reward_name)
      if reward_name.nil?
        fail ArgumentError, 'reward_name cannot be nil'
      end

      @reward_name = reward_name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["unlocked", "used"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] unlocked_at Value to be assigned
    def unlocked_at=(unlocked_at)
      if unlocked_at.nil?
        fail ArgumentError, 'unlocked_at cannot be nil'
      end

      @unlocked_at = unlocked_at
    end

    # Custom attribute writer method with validation
    # @param [Object] loyalty_card_identifier Value to be assigned
    def loyalty_card_identifier=(loyalty_card_identifier)
      if loyalty_card_identifier.nil?
        fail ArgumentError, 'loyalty_card_identifier cannot be nil'
      end

      if loyalty_card_identifier.to_s.length > 108
        fail ArgumentError, 'invalid value for "loyalty_card_identifier", the character length must be smaller than or equal to 108.'
      end

      if loyalty_card_identifier.to_s.length < 4
        fail ArgumentError, 'invalid value for "loyalty_card_identifier", the character length must be greater than or equal to 4.'
      end

      pattern = Regexp.new(/^[A-Za-z0-9._%+@-]+$/)
      if loyalty_card_identifier !~ pattern
        fail ArgumentError, "invalid value for \"loyalty_card_identifier\", must conform to the pattern #{pattern}."
      end

      @loyalty_card_identifier = loyalty_card_identifier
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          reward_id == o.reward_id &&
          reward_name == o.reward_name &&
          status == o.status &&
          unlocked_at == o.unlocked_at &&
          unlocked_by_integration_id == o.unlocked_by_integration_id &&
          used_at == o.used_at &&
          used_by_integration_id == o.used_by_integration_id &&
          loyalty_program_id == o.loyalty_program_id &&
          loyalty_card_identifier == o.loyalty_card_identifier
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, reward_id, reward_name, status, unlocked_at, unlocked_by_integration_id, used_at, used_by_integration_id, loyalty_program_id, loyalty_card_identifier].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
