=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module TalonOne
  # Contains all entities that might interest Talon.One integrations. 
  class IntegrationStateV2 < ApiModelBase
    attr_accessor :customer_session

    attr_accessor :customer_profile

    attr_accessor :event

    attr_accessor :loyalty

    attr_accessor :referral

    attr_accessor :coupons

    attr_accessor :triggered_campaigns

    # The effects generated by the rules in your running campaigns. See [API effects](https://docs.talon.one/docs/dev/integration-api/api-effects).
    attr_accessor :effects

    attr_accessor :rule_failure_reasons

    attr_accessor :created_coupons

    attr_accessor :created_referrals

    attr_accessor :awarded_giveaways

    attr_accessor :_return

    attr_accessor :previous_returns

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'customer_session' => :'customerSession',
        :'customer_profile' => :'customerProfile',
        :'event' => :'event',
        :'loyalty' => :'loyalty',
        :'referral' => :'referral',
        :'coupons' => :'coupons',
        :'triggered_campaigns' => :'triggeredCampaigns',
        :'effects' => :'effects',
        :'rule_failure_reasons' => :'ruleFailureReasons',
        :'created_coupons' => :'createdCoupons',
        :'created_referrals' => :'createdReferrals',
        :'awarded_giveaways' => :'awardedGiveaways',
        :'_return' => :'return',
        :'previous_returns' => :'previousReturns'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'customer_session' => :'CustomerSessionV2',
        :'customer_profile' => :'CustomerProfile',
        :'event' => :'Event',
        :'loyalty' => :'Loyalty',
        :'referral' => :'InventoryReferral',
        :'coupons' => :'Array<IntegrationCoupon>',
        :'triggered_campaigns' => :'Array<Campaign>',
        :'effects' => :'Array<Effect>',
        :'rule_failure_reasons' => :'Array<RuleFailureReason>',
        :'created_coupons' => :'Array<Coupon>',
        :'created_referrals' => :'Array<Referral>',
        :'awarded_giveaways' => :'Array<Giveaway>',
        :'_return' => :'ModelReturn',
        :'previous_returns' => :'Array<ModelReturn>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::IntegrationStateV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::IntegrationStateV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'customer_session')
        self.customer_session = attributes[:'customer_session']
      end

      if attributes.key?(:'customer_profile')
        self.customer_profile = attributes[:'customer_profile']
      end

      if attributes.key?(:'event')
        self.event = attributes[:'event']
      end

      if attributes.key?(:'loyalty')
        self.loyalty = attributes[:'loyalty']
      end

      if attributes.key?(:'referral')
        self.referral = attributes[:'referral']
      end

      if attributes.key?(:'coupons')
        if (value = attributes[:'coupons']).is_a?(Array)
          self.coupons = value
        end
      end

      if attributes.key?(:'triggered_campaigns')
        if (value = attributes[:'triggered_campaigns']).is_a?(Array)
          self.triggered_campaigns = value
        end
      end

      if attributes.key?(:'effects')
        if (value = attributes[:'effects']).is_a?(Array)
          self.effects = value
        end
      else
        self.effects = nil
      end

      if attributes.key?(:'rule_failure_reasons')
        if (value = attributes[:'rule_failure_reasons']).is_a?(Array)
          self.rule_failure_reasons = value
        end
      end

      if attributes.key?(:'created_coupons')
        if (value = attributes[:'created_coupons']).is_a?(Array)
          self.created_coupons = value
        end
      else
        self.created_coupons = nil
      end

      if attributes.key?(:'created_referrals')
        if (value = attributes[:'created_referrals']).is_a?(Array)
          self.created_referrals = value
        end
      else
        self.created_referrals = nil
      end

      if attributes.key?(:'awarded_giveaways')
        if (value = attributes[:'awarded_giveaways']).is_a?(Array)
          self.awarded_giveaways = value
        end
      end

      if attributes.key?(:'_return')
        self._return = attributes[:'_return']
      end

      if attributes.key?(:'previous_returns')
        if (value = attributes[:'previous_returns']).is_a?(Array)
          self.previous_returns = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @effects.nil?
        invalid_properties.push('invalid value for "effects", effects cannot be nil.')
      end

      if @created_coupons.nil?
        invalid_properties.push('invalid value for "created_coupons", created_coupons cannot be nil.')
      end

      if @created_referrals.nil?
        invalid_properties.push('invalid value for "created_referrals", created_referrals cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @effects.nil?
      return false if @created_coupons.nil?
      return false if @created_referrals.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] effects Value to be assigned
    def effects=(effects)
      if effects.nil?
        fail ArgumentError, 'effects cannot be nil'
      end

      @effects = effects
    end

    # Custom attribute writer method with validation
    # @param [Object] created_coupons Value to be assigned
    def created_coupons=(created_coupons)
      if created_coupons.nil?
        fail ArgumentError, 'created_coupons cannot be nil'
      end

      @created_coupons = created_coupons
    end

    # Custom attribute writer method with validation
    # @param [Object] created_referrals Value to be assigned
    def created_referrals=(created_referrals)
      if created_referrals.nil?
        fail ArgumentError, 'created_referrals cannot be nil'
      end

      @created_referrals = created_referrals
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          customer_session == o.customer_session &&
          customer_profile == o.customer_profile &&
          event == o.event &&
          loyalty == o.loyalty &&
          referral == o.referral &&
          coupons == o.coupons &&
          triggered_campaigns == o.triggered_campaigns &&
          effects == o.effects &&
          rule_failure_reasons == o.rule_failure_reasons &&
          created_coupons == o.created_coupons &&
          created_referrals == o.created_referrals &&
          awarded_giveaways == o.awarded_giveaways &&
          _return == o._return &&
          previous_returns == o.previous_returns
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [customer_session, customer_profile, event, loyalty, referral, coupons, triggered_campaigns, effects, rule_failure_reasons, created_coupons, created_referrals, awarded_giveaways, _return, previous_returns].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
