=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module TalonOne
  # The properties specific to effects for changing the expiry dates of loyalty ledger entries.
  class LoyaltyLedgerEntryExpiryDateChange < ApiModelBase
    # The identifier of the transaction affected by the extension or update.
    attr_accessor :transaction_uuid

    # Expiry date of the transactions before applying the extension or update.
    attr_accessor :previous_expiry_date

    # Expiry date of the transaction after applying the extension or update.
    attr_accessor :new_expiry_date

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'transaction_uuid' => :'transactionUUID',
        :'previous_expiry_date' => :'previousExpiryDate',
        :'new_expiry_date' => :'newExpiryDate'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'transaction_uuid' => :'String',
        :'previous_expiry_date' => :'Time',
        :'new_expiry_date' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::LoyaltyLedgerEntryExpiryDateChange` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::LoyaltyLedgerEntryExpiryDateChange`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'transaction_uuid')
        self.transaction_uuid = attributes[:'transaction_uuid']
      else
        self.transaction_uuid = nil
      end

      if attributes.key?(:'previous_expiry_date')
        self.previous_expiry_date = attributes[:'previous_expiry_date']
      end

      if attributes.key?(:'new_expiry_date')
        self.new_expiry_date = attributes[:'new_expiry_date']
      else
        self.new_expiry_date = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @transaction_uuid.nil?
        invalid_properties.push('invalid value for "transaction_uuid", transaction_uuid cannot be nil.')
      end

      if @new_expiry_date.nil?
        invalid_properties.push('invalid value for "new_expiry_date", new_expiry_date cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @transaction_uuid.nil?
      return false if @new_expiry_date.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] transaction_uuid Value to be assigned
    def transaction_uuid=(transaction_uuid)
      if transaction_uuid.nil?
        fail ArgumentError, 'transaction_uuid cannot be nil'
      end

      @transaction_uuid = transaction_uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] new_expiry_date Value to be assigned
    def new_expiry_date=(new_expiry_date)
      if new_expiry_date.nil?
        fail ArgumentError, 'new_expiry_date cannot be nil'
      end

      @new_expiry_date = new_expiry_date
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          transaction_uuid == o.transaction_uuid &&
          previous_expiry_date == o.previous_expiry_date &&
          new_expiry_date == o.new_expiry_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [transaction_uuid, previous_expiry_date, new_expiry_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
