=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module TalonOne
  class MCPOAuthServerMetadata < ApiModelBase
    # The authorization server's issuer identifier (its base URL).
    attr_accessor :issuer

    # URL of the authorization endpoint.
    attr_accessor :authorization_endpoint

    # URL of the token endpoint.
    attr_accessor :token_endpoint

    # URL of the client registration endpoint.
    attr_accessor :registration_endpoint

    # List of supported OAuth2 response types.
    attr_accessor :response_types_supported

    # List of supported OAuth2 grant types.
    attr_accessor :grant_types_supported

    # List of supported PKCE code challenge methods.
    attr_accessor :code_challenge_methods_supported

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'issuer' => :'issuer',
        :'authorization_endpoint' => :'authorization_endpoint',
        :'token_endpoint' => :'token_endpoint',
        :'registration_endpoint' => :'registration_endpoint',
        :'response_types_supported' => :'response_types_supported',
        :'grant_types_supported' => :'grant_types_supported',
        :'code_challenge_methods_supported' => :'code_challenge_methods_supported'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'issuer' => :'String',
        :'authorization_endpoint' => :'String',
        :'token_endpoint' => :'String',
        :'registration_endpoint' => :'String',
        :'response_types_supported' => :'Array<String>',
        :'grant_types_supported' => :'Array<String>',
        :'code_challenge_methods_supported' => :'Array<String>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::MCPOAuthServerMetadata` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::MCPOAuthServerMetadata`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'issuer')
        self.issuer = attributes[:'issuer']
      else
        self.issuer = nil
      end

      if attributes.key?(:'authorization_endpoint')
        self.authorization_endpoint = attributes[:'authorization_endpoint']
      else
        self.authorization_endpoint = nil
      end

      if attributes.key?(:'token_endpoint')
        self.token_endpoint = attributes[:'token_endpoint']
      else
        self.token_endpoint = nil
      end

      if attributes.key?(:'registration_endpoint')
        self.registration_endpoint = attributes[:'registration_endpoint']
      else
        self.registration_endpoint = nil
      end

      if attributes.key?(:'response_types_supported')
        if (value = attributes[:'response_types_supported']).is_a?(Array)
          self.response_types_supported = value
        end
      else
        self.response_types_supported = nil
      end

      if attributes.key?(:'grant_types_supported')
        if (value = attributes[:'grant_types_supported']).is_a?(Array)
          self.grant_types_supported = value
        end
      else
        self.grant_types_supported = nil
      end

      if attributes.key?(:'code_challenge_methods_supported')
        if (value = attributes[:'code_challenge_methods_supported']).is_a?(Array)
          self.code_challenge_methods_supported = value
        end
      else
        self.code_challenge_methods_supported = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @issuer.nil?
        invalid_properties.push('invalid value for "issuer", issuer cannot be nil.')
      end

      if @authorization_endpoint.nil?
        invalid_properties.push('invalid value for "authorization_endpoint", authorization_endpoint cannot be nil.')
      end

      if @token_endpoint.nil?
        invalid_properties.push('invalid value for "token_endpoint", token_endpoint cannot be nil.')
      end

      if @registration_endpoint.nil?
        invalid_properties.push('invalid value for "registration_endpoint", registration_endpoint cannot be nil.')
      end

      if @response_types_supported.nil?
        invalid_properties.push('invalid value for "response_types_supported", response_types_supported cannot be nil.')
      end

      if @grant_types_supported.nil?
        invalid_properties.push('invalid value for "grant_types_supported", grant_types_supported cannot be nil.')
      end

      if @code_challenge_methods_supported.nil?
        invalid_properties.push('invalid value for "code_challenge_methods_supported", code_challenge_methods_supported cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @issuer.nil?
      return false if @authorization_endpoint.nil?
      return false if @token_endpoint.nil?
      return false if @registration_endpoint.nil?
      return false if @response_types_supported.nil?
      return false if @grant_types_supported.nil?
      return false if @code_challenge_methods_supported.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] issuer Value to be assigned
    def issuer=(issuer)
      if issuer.nil?
        fail ArgumentError, 'issuer cannot be nil'
      end

      @issuer = issuer
    end

    # Custom attribute writer method with validation
    # @param [Object] authorization_endpoint Value to be assigned
    def authorization_endpoint=(authorization_endpoint)
      if authorization_endpoint.nil?
        fail ArgumentError, 'authorization_endpoint cannot be nil'
      end

      @authorization_endpoint = authorization_endpoint
    end

    # Custom attribute writer method with validation
    # @param [Object] token_endpoint Value to be assigned
    def token_endpoint=(token_endpoint)
      if token_endpoint.nil?
        fail ArgumentError, 'token_endpoint cannot be nil'
      end

      @token_endpoint = token_endpoint
    end

    # Custom attribute writer method with validation
    # @param [Object] registration_endpoint Value to be assigned
    def registration_endpoint=(registration_endpoint)
      if registration_endpoint.nil?
        fail ArgumentError, 'registration_endpoint cannot be nil'
      end

      @registration_endpoint = registration_endpoint
    end

    # Custom attribute writer method with validation
    # @param [Object] response_types_supported Value to be assigned
    def response_types_supported=(response_types_supported)
      if response_types_supported.nil?
        fail ArgumentError, 'response_types_supported cannot be nil'
      end

      @response_types_supported = response_types_supported
    end

    # Custom attribute writer method with validation
    # @param [Object] grant_types_supported Value to be assigned
    def grant_types_supported=(grant_types_supported)
      if grant_types_supported.nil?
        fail ArgumentError, 'grant_types_supported cannot be nil'
      end

      @grant_types_supported = grant_types_supported
    end

    # Custom attribute writer method with validation
    # @param [Object] code_challenge_methods_supported Value to be assigned
    def code_challenge_methods_supported=(code_challenge_methods_supported)
      if code_challenge_methods_supported.nil?
        fail ArgumentError, 'code_challenge_methods_supported cannot be nil'
      end

      @code_challenge_methods_supported = code_challenge_methods_supported
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          issuer == o.issuer &&
          authorization_endpoint == o.authorization_endpoint &&
          token_endpoint == o.token_endpoint &&
          registration_endpoint == o.registration_endpoint &&
          response_types_supported == o.response_types_supported &&
          grant_types_supported == o.grant_types_supported &&
          code_challenge_methods_supported == o.code_challenge_methods_supported
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [issuer, authorization_endpoint, token_endpoint, registration_endpoint, response_types_supported, grant_types_supported, code_challenge_methods_supported].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
