=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module TalonOne
  class NewCouponCreationJob < ApiModelBase
    # The number of times the coupon code can be redeemed. `0` means unlimited redemptions but any campaign usage limits will still apply. 
    attr_accessor :usage_limit

    # The total discount value that the code can give. Typically used to represent a gift card value. 
    attr_accessor :discount_limit

    # The number of reservations that can be made with this coupon code. 
    attr_accessor :reservation_limit

    # Timestamp at which point the coupon becomes valid.
    attr_accessor :start_date

    # Expiration date of the coupon. Coupon never expires if this is omitted.
    attr_accessor :expiry_date

    # The number of new coupon codes to generate for the campaign.
    attr_accessor :number_of_coupons

    attr_accessor :coupon_settings

    # Arbitrary properties associated with coupons.
    attr_accessor :attributes

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'usage_limit' => :'usageLimit',
        :'discount_limit' => :'discountLimit',
        :'reservation_limit' => :'reservationLimit',
        :'start_date' => :'startDate',
        :'expiry_date' => :'expiryDate',
        :'number_of_coupons' => :'numberOfCoupons',
        :'coupon_settings' => :'couponSettings',
        :'attributes' => :'attributes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'usage_limit' => :'Integer',
        :'discount_limit' => :'Float',
        :'reservation_limit' => :'Integer',
        :'start_date' => :'Time',
        :'expiry_date' => :'Time',
        :'number_of_coupons' => :'Integer',
        :'coupon_settings' => :'CodeGeneratorSettings',
        :'attributes' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'CouponConstraints'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::NewCouponCreationJob` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::NewCouponCreationJob`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'usage_limit')
        self.usage_limit = attributes[:'usage_limit']
      end

      if attributes.key?(:'discount_limit')
        self.discount_limit = attributes[:'discount_limit']
      end

      if attributes.key?(:'reservation_limit')
        self.reservation_limit = attributes[:'reservation_limit']
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      end

      if attributes.key?(:'expiry_date')
        self.expiry_date = attributes[:'expiry_date']
      end

      if attributes.key?(:'number_of_coupons')
        self.number_of_coupons = attributes[:'number_of_coupons']
      else
        self.number_of_coupons = nil
      end

      if attributes.key?(:'coupon_settings')
        self.coupon_settings = attributes[:'coupon_settings']
      end

      if attributes.key?(:'attributes')
        self.attributes = attributes[:'attributes']
      else
        self.attributes = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@usage_limit.nil? && @usage_limit > 999999
        invalid_properties.push('invalid value for "usage_limit", must be smaller than or equal to 999999.')
      end

      if !@usage_limit.nil? && @usage_limit < 0
        invalid_properties.push('invalid value for "usage_limit", must be greater than or equal to 0.')
      end

      if !@discount_limit.nil? && @discount_limit > 1000000000000000
        invalid_properties.push('invalid value for "discount_limit", must be smaller than or equal to 1000000000000000.')
      end

      if !@discount_limit.nil? && @discount_limit < 0
        invalid_properties.push('invalid value for "discount_limit", must be greater than or equal to 0.')
      end

      if !@reservation_limit.nil? && @reservation_limit > 999999
        invalid_properties.push('invalid value for "reservation_limit", must be smaller than or equal to 999999.')
      end

      if !@reservation_limit.nil? && @reservation_limit < 0
        invalid_properties.push('invalid value for "reservation_limit", must be greater than or equal to 0.')
      end

      if @number_of_coupons.nil?
        invalid_properties.push('invalid value for "number_of_coupons", number_of_coupons cannot be nil.')
      end

      if @number_of_coupons > 5000000
        invalid_properties.push('invalid value for "number_of_coupons", must be smaller than or equal to 5000000.')
      end

      if @number_of_coupons < 1
        invalid_properties.push('invalid value for "number_of_coupons", must be greater than or equal to 1.')
      end

      if @attributes.nil?
        invalid_properties.push('invalid value for "attributes", attributes cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@usage_limit.nil? && @usage_limit > 999999
      return false if !@usage_limit.nil? && @usage_limit < 0
      return false if !@discount_limit.nil? && @discount_limit > 1000000000000000
      return false if !@discount_limit.nil? && @discount_limit < 0
      return false if !@reservation_limit.nil? && @reservation_limit > 999999
      return false if !@reservation_limit.nil? && @reservation_limit < 0
      return false if @number_of_coupons.nil?
      return false if @number_of_coupons > 5000000
      return false if @number_of_coupons < 1
      return false if @attributes.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] usage_limit Value to be assigned
    def usage_limit=(usage_limit)
      if usage_limit.nil?
        fail ArgumentError, 'usage_limit cannot be nil'
      end

      if usage_limit > 999999
        fail ArgumentError, 'invalid value for "usage_limit", must be smaller than or equal to 999999.'
      end

      if usage_limit < 0
        fail ArgumentError, 'invalid value for "usage_limit", must be greater than or equal to 0.'
      end

      @usage_limit = usage_limit
    end

    # Custom attribute writer method with validation
    # @param [Object] discount_limit Value to be assigned
    def discount_limit=(discount_limit)
      if discount_limit.nil?
        fail ArgumentError, 'discount_limit cannot be nil'
      end

      if discount_limit > 1000000000000000
        fail ArgumentError, 'invalid value for "discount_limit", must be smaller than or equal to 1000000000000000.'
      end

      if discount_limit < 0
        fail ArgumentError, 'invalid value for "discount_limit", must be greater than or equal to 0.'
      end

      @discount_limit = discount_limit
    end

    # Custom attribute writer method with validation
    # @param [Object] reservation_limit Value to be assigned
    def reservation_limit=(reservation_limit)
      if reservation_limit.nil?
        fail ArgumentError, 'reservation_limit cannot be nil'
      end

      if reservation_limit > 999999
        fail ArgumentError, 'invalid value for "reservation_limit", must be smaller than or equal to 999999.'
      end

      if reservation_limit < 0
        fail ArgumentError, 'invalid value for "reservation_limit", must be greater than or equal to 0.'
      end

      @reservation_limit = reservation_limit
    end

    # Custom attribute writer method with validation
    # @param [Object] number_of_coupons Value to be assigned
    def number_of_coupons=(number_of_coupons)
      if number_of_coupons.nil?
        fail ArgumentError, 'number_of_coupons cannot be nil'
      end

      if number_of_coupons > 5000000
        fail ArgumentError, 'invalid value for "number_of_coupons", must be smaller than or equal to 5000000.'
      end

      if number_of_coupons < 1
        fail ArgumentError, 'invalid value for "number_of_coupons", must be greater than or equal to 1.'
      end

      @number_of_coupons = number_of_coupons
    end

    # Custom attribute writer method with validation
    # @param [Object] attributes Value to be assigned
    def attributes=(attributes)
      if attributes.nil?
        fail ArgumentError, 'attributes cannot be nil'
      end

      @attributes = attributes
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          usage_limit == o.usage_limit &&
          discount_limit == o.discount_limit &&
          reservation_limit == o.reservation_limit &&
          start_date == o.start_date &&
          expiry_date == o.expiry_date &&
          number_of_coupons == o.number_of_coupons &&
          coupon_settings == o.coupon_settings &&
          attributes == o.attributes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [usage_limit, discount_limit, reservation_limit, start_date, expiry_date, number_of_coupons, coupon_settings, attributes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
