=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module TalonOne
  class NewWebhook < ApiModelBase
    # The IDs of the Applications in which this webhook is available. An empty array means the webhook is available in `All Applications`. 
    attr_accessor :application_ids

    # Name or title for this webhook.
    attr_accessor :title

    # A description of the webhook.
    attr_accessor :description

    # Indicates if the webhook is a draft.
    attr_accessor :draft

    # API method for this webhook.
    attr_accessor :verb

    # API URL (supports templating using parameters) for this webhook.
    attr_accessor :url

    # List of API HTTP headers for this webhook.
    attr_accessor :headers

    # API payload (supports templating using parameters) for this webhook.
    attr_accessor :payload

    # Array of template argument definitions.
    attr_accessor :params

    # Enables or disables webhook from showing in the Rule Builder.
    attr_accessor :enabled

    # The ID of the credential that this webhook is using.
    attr_accessor :authentication_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'application_ids' => :'applicationIds',
        :'title' => :'title',
        :'description' => :'description',
        :'draft' => :'draft',
        :'verb' => :'verb',
        :'url' => :'url',
        :'headers' => :'headers',
        :'payload' => :'payload',
        :'params' => :'params',
        :'enabled' => :'enabled',
        :'authentication_id' => :'authenticationId'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'application_ids' => :'Array<Integer>',
        :'title' => :'String',
        :'description' => :'String',
        :'draft' => :'Boolean',
        :'verb' => :'String',
        :'url' => :'String',
        :'headers' => :'Array<String>',
        :'payload' => :'String',
        :'params' => :'Array<TemplateArgDef>',
        :'enabled' => :'Boolean',
        :'authentication_id' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::NewWebhook` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::NewWebhook`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'application_ids')
        if (value = attributes[:'application_ids']).is_a?(Array)
          self.application_ids = value
        end
      else
        self.application_ids = nil
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'draft')
        self.draft = attributes[:'draft']
      else
        self.draft = nil
      end

      if attributes.key?(:'verb')
        self.verb = attributes[:'verb']
      else
        self.verb = nil
      end

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      else
        self.url = nil
      end

      if attributes.key?(:'headers')
        if (value = attributes[:'headers']).is_a?(Array)
          self.headers = value
        end
      else
        self.headers = nil
      end

      if attributes.key?(:'payload')
        self.payload = attributes[:'payload']
      end

      if attributes.key?(:'params')
        if (value = attributes[:'params']).is_a?(Array)
          self.params = value
        end
      else
        self.params = nil
      end

      if attributes.key?(:'enabled')
        self.enabled = attributes[:'enabled']
      else
        self.enabled = nil
      end

      if attributes.key?(:'authentication_id')
        self.authentication_id = attributes[:'authentication_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @application_ids.nil?
        invalid_properties.push('invalid value for "application_ids", application_ids cannot be nil.')
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      pattern = Regexp.new(/^[A-Za-z][A-Za-z0-9_.!~*'() -]*$/)
      if @title !~ pattern
        invalid_properties.push("invalid value for \"title\", must conform to the pattern #{pattern}.")
      end

      if @draft.nil?
        invalid_properties.push('invalid value for "draft", draft cannot be nil.')
      end

      if @verb.nil?
        invalid_properties.push('invalid value for "verb", verb cannot be nil.')
      end

      if @url.nil?
        invalid_properties.push('invalid value for "url", url cannot be nil.')
      end

      if @headers.nil?
        invalid_properties.push('invalid value for "headers", headers cannot be nil.')
      end

      if @params.nil?
        invalid_properties.push('invalid value for "params", params cannot be nil.')
      end

      if @enabled.nil?
        invalid_properties.push('invalid value for "enabled", enabled cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @application_ids.nil?
      return false if @title.nil?
      return false if @title !~ Regexp.new(/^[A-Za-z][A-Za-z0-9_.!~*'() -]*$/)
      return false if @draft.nil?
      return false if @verb.nil?
      verb_validator = EnumAttributeValidator.new('String', ["POST", "PUT", "GET", "DELETE", "PATCH"])
      return false unless verb_validator.valid?(@verb)
      return false if @url.nil?
      return false if @headers.nil?
      return false if @params.nil?
      return false if @enabled.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] application_ids Value to be assigned
    def application_ids=(application_ids)
      if application_ids.nil?
        fail ArgumentError, 'application_ids cannot be nil'
      end

      @application_ids = application_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      pattern = Regexp.new(/^[A-Za-z][A-Za-z0-9_.!~*'() -]*$/)
      if title !~ pattern
        fail ArgumentError, "invalid value for \"title\", must conform to the pattern #{pattern}."
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] draft Value to be assigned
    def draft=(draft)
      if draft.nil?
        fail ArgumentError, 'draft cannot be nil'
      end

      @draft = draft
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] verb Object to be assigned
    def verb=(verb)
      validator = EnumAttributeValidator.new('String', ["POST", "PUT", "GET", "DELETE", "PATCH"])
      unless validator.valid?(verb)
        fail ArgumentError, "invalid value for \"verb\", must be one of #{validator.allowable_values}."
      end
      @verb = verb
    end

    # Custom attribute writer method with validation
    # @param [Object] url Value to be assigned
    def url=(url)
      if url.nil?
        fail ArgumentError, 'url cannot be nil'
      end

      @url = url
    end

    # Custom attribute writer method with validation
    # @param [Object] headers Value to be assigned
    def headers=(headers)
      if headers.nil?
        fail ArgumentError, 'headers cannot be nil'
      end

      @headers = headers
    end

    # Custom attribute writer method with validation
    # @param [Object] params Value to be assigned
    def params=(params)
      if params.nil?
        fail ArgumentError, 'params cannot be nil'
      end

      @params = params
    end

    # Custom attribute writer method with validation
    # @param [Object] enabled Value to be assigned
    def enabled=(enabled)
      if enabled.nil?
        fail ArgumentError, 'enabled cannot be nil'
      end

      @enabled = enabled
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          application_ids == o.application_ids &&
          title == o.title &&
          description == o.description &&
          draft == o.draft &&
          verb == o.verb &&
          url == o.url &&
          headers == o.headers &&
          payload == o.payload &&
          params == o.params &&
          enabled == o.enabled &&
          authentication_id == o.authentication_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [application_ids, title, description, draft, verb, url, headers, payload, params, enabled, authentication_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
