=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module TalonOne
  # Outbound notification or webhook message with its shared request details.
  class OutboundMessage < ApiModelBase
    # UUID of the outbound message.
    attr_accessor :uuid

    # ID of the notification that produced the outbound request.
    attr_accessor :notification_id

    # Name of the notification that produced the outbound request.
    attr_accessor :notification_name

    # ID of the webhook that produced the outbound request.
    attr_accessor :webhook_id

    # The name of the webhook that produced the outbound request.
    attr_accessor :webhook_name

    # Type of notification that produced the outbound request.
    attr_accessor :notification_type

    # ID of the Application associated with the outbound request.
    attr_accessor :application_id

    # ID of the loyalty program associated with the outbound request.
    attr_accessor :loyalty_program_id

    attr_accessor :request

    # Timestamp of the first log entry for this message.
    attr_accessor :first_log_at

    # Timestamp of the last log entry for this message.
    attr_accessor :last_log_at

    # HTTP status code from the latest response.
    attr_accessor :last_response_code

    attr_accessor :status

    # Number of retries.
    attr_accessor :retry_count

    # Log entries for this message. Omitted when `includeLogs=false`.
    attr_accessor :responses

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'uuid' => :'uuid',
        :'notification_id' => :'notificationId',
        :'notification_name' => :'notificationName',
        :'webhook_id' => :'webhookId',
        :'webhook_name' => :'webhookName',
        :'notification_type' => :'notificationType',
        :'application_id' => :'applicationId',
        :'loyalty_program_id' => :'loyaltyProgramId',
        :'request' => :'request',
        :'first_log_at' => :'firstLogAt',
        :'last_log_at' => :'lastLogAt',
        :'last_response_code' => :'lastResponseCode',
        :'status' => :'status',
        :'retry_count' => :'retryCount',
        :'responses' => :'responses'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'uuid' => :'String',
        :'notification_id' => :'Integer',
        :'notification_name' => :'String',
        :'webhook_id' => :'Integer',
        :'webhook_name' => :'String',
        :'notification_type' => :'String',
        :'application_id' => :'Integer',
        :'loyalty_program_id' => :'Integer',
        :'request' => :'OutboundLogRequest',
        :'first_log_at' => :'Time',
        :'last_log_at' => :'Time',
        :'last_response_code' => :'Integer',
        :'status' => :'String',
        :'retry_count' => :'Integer',
        :'responses' => :'Array<OutboundMessageResponse>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'OutboundLogBase'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::OutboundMessage` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::OutboundMessage`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'uuid')
        self.uuid = attributes[:'uuid']
      else
        self.uuid = nil
      end

      if attributes.key?(:'notification_id')
        self.notification_id = attributes[:'notification_id']
      end

      if attributes.key?(:'notification_name')
        self.notification_name = attributes[:'notification_name']
      end

      if attributes.key?(:'webhook_id')
        self.webhook_id = attributes[:'webhook_id']
      end

      if attributes.key?(:'webhook_name')
        self.webhook_name = attributes[:'webhook_name']
      end

      if attributes.key?(:'notification_type')
        self.notification_type = attributes[:'notification_type']
      else
        self.notification_type = nil
      end

      if attributes.key?(:'application_id')
        self.application_id = attributes[:'application_id']
      end

      if attributes.key?(:'loyalty_program_id')
        self.loyalty_program_id = attributes[:'loyalty_program_id']
      end

      if attributes.key?(:'request')
        self.request = attributes[:'request']
      end

      if attributes.key?(:'first_log_at')
        self.first_log_at = attributes[:'first_log_at']
      else
        self.first_log_at = nil
      end

      if attributes.key?(:'last_log_at')
        self.last_log_at = attributes[:'last_log_at']
      else
        self.last_log_at = nil
      end

      if attributes.key?(:'last_response_code')
        self.last_response_code = attributes[:'last_response_code']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'retry_count')
        self.retry_count = attributes[:'retry_count']
      end

      if attributes.key?(:'responses')
        if (value = attributes[:'responses']).is_a?(Array)
          self.responses = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @uuid.nil?
        invalid_properties.push('invalid value for "uuid", uuid cannot be nil.')
      end

      if @notification_type.nil?
        invalid_properties.push('invalid value for "notification_type", notification_type cannot be nil.')
      end

      if @first_log_at.nil?
        invalid_properties.push('invalid value for "first_log_at", first_log_at cannot be nil.')
      end

      if @last_log_at.nil?
        invalid_properties.push('invalid value for "last_log_at", last_log_at cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @uuid.nil?
      return false if @notification_type.nil?
      return false if @first_log_at.nil?
      return false if @last_log_at.nil?
      return false if @status.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] uuid Value to be assigned
    def uuid=(uuid)
      if uuid.nil?
        fail ArgumentError, 'uuid cannot be nil'
      end

      @uuid = uuid
    end

    # Custom attribute writer method with validation
    # @param [Object] notification_type Value to be assigned
    def notification_type=(notification_type)
      if notification_type.nil?
        fail ArgumentError, 'notification_type cannot be nil'
      end

      @notification_type = notification_type
    end

    # Custom attribute writer method with validation
    # @param [Object] first_log_at Value to be assigned
    def first_log_at=(first_log_at)
      if first_log_at.nil?
        fail ArgumentError, 'first_log_at cannot be nil'
      end

      @first_log_at = first_log_at
    end

    # Custom attribute writer method with validation
    # @param [Object] last_log_at Value to be assigned
    def last_log_at=(last_log_at)
      if last_log_at.nil?
        fail ArgumentError, 'last_log_at cannot be nil'
      end

      @last_log_at = last_log_at
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          uuid == o.uuid &&
          notification_id == o.notification_id &&
          notification_name == o.notification_name &&
          webhook_id == o.webhook_id &&
          webhook_name == o.webhook_name &&
          notification_type == o.notification_type &&
          application_id == o.application_id &&
          loyalty_program_id == o.loyalty_program_id &&
          request == o.request &&
          first_log_at == o.first_log_at &&
          last_log_at == o.last_log_at &&
          last_response_code == o.last_response_code &&
          status == o.status &&
          retry_count == o.retry_count &&
          responses == o.responses
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [uuid, notification_id, notification_name, webhook_id, webhook_name, notification_type, application_id, loyalty_program_id, request, first_log_at, last_log_at, last_response_code, status, retry_count, responses].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
