=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.17.0

=end

require 'date'
require 'time'

module TalonOne
  class PendingActivePointsData < ApiModelBase
    # The ID of the loyalty program.
    attr_accessor :loyalty_program_id

    # The ID of the subledger, when applicable. If this field is empty, the main ledger is used.
    attr_accessor :subledger_id

    # The integration ID of the customer profile whose loyalty points are becoming active.
    attr_accessor :customer_profile_id

    # The amount of pending loyalty points becoming active.
    attr_accessor :points

    # The date and time the loyalty points become active.
    attr_accessor :active_on

    # The date and time the loyalty points expire.
    attr_accessor :expire_on

    # The integration ID of the session through which the points were earned.
    attr_accessor :session_integration_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'loyalty_program_id' => :'LoyaltyProgramID',
        :'subledger_id' => :'SubledgerID',
        :'customer_profile_id' => :'CustomerProfileID',
        :'points' => :'Points',
        :'active_on' => :'ActiveOn',
        :'expire_on' => :'ExpireOn',
        :'session_integration_id' => :'SessionIntegrationID'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'loyalty_program_id' => :'Integer',
        :'subledger_id' => :'String',
        :'customer_profile_id' => :'String',
        :'points' => :'Float',
        :'active_on' => :'Time',
        :'expire_on' => :'Time',
        :'session_integration_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::PendingActivePointsData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::PendingActivePointsData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'loyalty_program_id')
        self.loyalty_program_id = attributes[:'loyalty_program_id']
      else
        self.loyalty_program_id = nil
      end

      if attributes.key?(:'subledger_id')
        self.subledger_id = attributes[:'subledger_id']
      else
        self.subledger_id = ''
      end

      if attributes.key?(:'customer_profile_id')
        self.customer_profile_id = attributes[:'customer_profile_id']
      else
        self.customer_profile_id = nil
      end

      if attributes.key?(:'points')
        self.points = attributes[:'points']
      else
        self.points = nil
      end

      if attributes.key?(:'active_on')
        self.active_on = attributes[:'active_on']
      end

      if attributes.key?(:'expire_on')
        self.expire_on = attributes[:'expire_on']
      end

      if attributes.key?(:'session_integration_id')
        self.session_integration_id = attributes[:'session_integration_id']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @loyalty_program_id.nil?
        invalid_properties.push('invalid value for "loyalty_program_id", loyalty_program_id cannot be nil.')
      end

      if @loyalty_program_id < 1
        invalid_properties.push('invalid value for "loyalty_program_id", must be greater than or equal to 1.')
      end

      if @subledger_id.nil?
        invalid_properties.push('invalid value for "subledger_id", subledger_id cannot be nil.')
      end

      if @customer_profile_id.nil?
        invalid_properties.push('invalid value for "customer_profile_id", customer_profile_id cannot be nil.')
      end

      if @points.nil?
        invalid_properties.push('invalid value for "points", points cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @loyalty_program_id.nil?
      return false if @loyalty_program_id < 1
      return false if @subledger_id.nil?
      return false if @customer_profile_id.nil?
      return false if @points.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] loyalty_program_id Value to be assigned
    def loyalty_program_id=(loyalty_program_id)
      if loyalty_program_id.nil?
        fail ArgumentError, 'loyalty_program_id cannot be nil'
      end

      if loyalty_program_id < 1
        fail ArgumentError, 'invalid value for "loyalty_program_id", must be greater than or equal to 1.'
      end

      @loyalty_program_id = loyalty_program_id
    end

    # Custom attribute writer method with validation
    # @param [Object] subledger_id Value to be assigned
    def subledger_id=(subledger_id)
      if subledger_id.nil?
        fail ArgumentError, 'subledger_id cannot be nil'
      end

      @subledger_id = subledger_id
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_profile_id Value to be assigned
    def customer_profile_id=(customer_profile_id)
      if customer_profile_id.nil?
        fail ArgumentError, 'customer_profile_id cannot be nil'
      end

      @customer_profile_id = customer_profile_id
    end

    # Custom attribute writer method with validation
    # @param [Object] points Value to be assigned
    def points=(points)
      if points.nil?
        fail ArgumentError, 'points cannot be nil'
      end

      @points = points
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          loyalty_program_id == o.loyalty_program_id &&
          subledger_id == o.subledger_id &&
          customer_profile_id == o.customer_profile_id &&
          points == o.points &&
          active_on == o.active_on &&
          expire_on == o.expire_on &&
          session_integration_id == o.session_integration_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [loyalty_program_id, subledger_id, customer_profile_id, points, active_on, expire_on, session_integration_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
