=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'date'
require 'time'

module TalonOne
  class PriceType < ApiModelBase
    # The internal ID of this entity.
    attr_accessor :id

    # The time this entity was created.
    attr_accessor :created

    # The ID of the account that owns this price type.
    attr_accessor :account_id

    # The API name of the price type. This is an immutable value.
    attr_accessor :name

    # The name displayed in the Campaign Manager for the price type.
    attr_accessor :title

    # A description of the price type.
    attr_accessor :description

    # The date and time when the price type was last modified.
    attr_accessor :modified

    # A list of the IDs of the catalogs that are subscribed to this price type.
    attr_accessor :subscribed_catalogs_ids

    # A list of the IDs of the audiences targeted by this price type.
    attr_accessor :targeted_audiences_ids

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'created' => :'created',
        :'account_id' => :'accountId',
        :'name' => :'name',
        :'title' => :'title',
        :'description' => :'description',
        :'modified' => :'modified',
        :'subscribed_catalogs_ids' => :'subscribedCatalogsIds',
        :'targeted_audiences_ids' => :'targetedAudiencesIds'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'created' => :'Time',
        :'account_id' => :'Integer',
        :'name' => :'String',
        :'title' => :'String',
        :'description' => :'String',
        :'modified' => :'Time',
        :'subscribed_catalogs_ids' => :'Array<Integer>',
        :'targeted_audiences_ids' => :'Array<Integer>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # List of class defined in allOf (OpenAPI v3)
    def self.openapi_all_of
      [
      :'Entity'
      ]
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::PriceType` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::PriceType`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'created')
        self.created = attributes[:'created']
      else
        self.created = nil
      end

      if attributes.key?(:'account_id')
        self.account_id = attributes[:'account_id']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end

      if attributes.key?(:'title')
        self.title = attributes[:'title']
      else
        self.title = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      end

      if attributes.key?(:'modified')
        self.modified = attributes[:'modified']
      else
        self.modified = nil
      end

      if attributes.key?(:'subscribed_catalogs_ids')
        if (value = attributes[:'subscribed_catalogs_ids']).is_a?(Array)
          self.subscribed_catalogs_ids = value
        end
      else
        self.subscribed_catalogs_ids = nil
      end

      if attributes.key?(:'targeted_audiences_ids')
        if (value = attributes[:'targeted_audiences_ids']).is_a?(Array)
          self.targeted_audiences_ids = value
        end
      else
        self.targeted_audiences_ids = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @created.nil?
        invalid_properties.push('invalid value for "created", created cannot be nil.')
      end

      if @name.nil?
        invalid_properties.push('invalid value for "name", name cannot be nil.')
      end

      pattern = Regexp.new(/^[A-Za-z]\w*$/)
      if @name !~ pattern
        invalid_properties.push("invalid value for \"name\", must conform to the pattern #{pattern}.")
      end

      if @title.nil?
        invalid_properties.push('invalid value for "title", title cannot be nil.')
      end

      if @modified.nil?
        invalid_properties.push('invalid value for "modified", modified cannot be nil.')
      end

      if @subscribed_catalogs_ids.nil?
        invalid_properties.push('invalid value for "subscribed_catalogs_ids", subscribed_catalogs_ids cannot be nil.')
      end

      if @targeted_audiences_ids.nil?
        invalid_properties.push('invalid value for "targeted_audiences_ids", targeted_audiences_ids cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @created.nil?
      return false if @name.nil?
      return false if @name !~ Regexp.new(/^[A-Za-z]\w*$/)
      return false if @title.nil?
      return false if @modified.nil?
      return false if @subscribed_catalogs_ids.nil?
      return false if @targeted_audiences_ids.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] created Value to be assigned
    def created=(created)
      if created.nil?
        fail ArgumentError, 'created cannot be nil'
      end

      @created = created
    end

    # Custom attribute writer method with validation
    # @param [Object] name Value to be assigned
    def name=(name)
      if name.nil?
        fail ArgumentError, 'name cannot be nil'
      end

      pattern = Regexp.new(/^[A-Za-z]\w*$/)
      if name !~ pattern
        fail ArgumentError, "invalid value for \"name\", must conform to the pattern #{pattern}."
      end

      @name = name
    end

    # Custom attribute writer method with validation
    # @param [Object] title Value to be assigned
    def title=(title)
      if title.nil?
        fail ArgumentError, 'title cannot be nil'
      end

      @title = title
    end

    # Custom attribute writer method with validation
    # @param [Object] modified Value to be assigned
    def modified=(modified)
      if modified.nil?
        fail ArgumentError, 'modified cannot be nil'
      end

      @modified = modified
    end

    # Custom attribute writer method with validation
    # @param [Object] subscribed_catalogs_ids Value to be assigned
    def subscribed_catalogs_ids=(subscribed_catalogs_ids)
      if subscribed_catalogs_ids.nil?
        fail ArgumentError, 'subscribed_catalogs_ids cannot be nil'
      end

      @subscribed_catalogs_ids = subscribed_catalogs_ids
    end

    # Custom attribute writer method with validation
    # @param [Object] targeted_audiences_ids Value to be assigned
    def targeted_audiences_ids=(targeted_audiences_ids)
      if targeted_audiences_ids.nil?
        fail ArgumentError, 'targeted_audiences_ids cannot be nil'
      end

      @targeted_audiences_ids = targeted_audiences_ids
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          created == o.created &&
          account_id == o.account_id &&
          name == o.name &&
          title == o.title &&
          description == o.description &&
          modified == o.modified &&
          subscribed_catalogs_ids == o.subscribed_catalogs_ids &&
          targeted_audiences_ids == o.targeted_audiences_ids
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, created, account_id, name, title, description, modified, subscribed_catalogs_ids, targeted_audiences_ids].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
