=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module TalonOne
  # Details about why a rule failed.
  class RuleFailureReason < ApiModelBase
    # The ID of the campaign that contains the rule that failed.
    attr_accessor :campaign_id

    # The name of the campaign that contains the rule that failed.
    attr_accessor :campaign_name

    # The ID of the ruleset that contains the rule that failed.
    attr_accessor :ruleset_id

    # The ID of the coupon that was being evaluated at the time of the rule failure.
    attr_accessor :coupon_id

    # The code of the coupon that was being evaluated at the time of the rule failure.
    attr_accessor :coupon_value

    # The ID of the referral that was being evaluated at the time of the rule failure.
    attr_accessor :referral_id

    # The code of the referral that was being evaluated at the time of the rule failure.
    attr_accessor :referral_value

    # The index of the rule that failed within the ruleset.
    attr_accessor :rule_index

    # The name of the rule that failed within the ruleset.
    attr_accessor :rule_name

    # The index of the condition that failed.
    attr_accessor :condition_index

    # The index of the effect that failed.
    attr_accessor :effect_index

    # More details about the failure.
    attr_accessor :details

    # The ID of the evaluation group. For more information, see [Managing campaign evaluation](https://docs.talon.one/docs/product/applications/managing-campaign-evaluation).
    attr_accessor :evaluation_group_id

    # The evaluation mode of the evaluation group. For more information, see [Managing campaign evaluation](https://docs.talon.one/docs/product/applications/managing-campaign-
    attr_accessor :evaluation_group_mode

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'campaign_id' => :'campaignID',
        :'campaign_name' => :'campaignName',
        :'ruleset_id' => :'rulesetID',
        :'coupon_id' => :'couponID',
        :'coupon_value' => :'couponValue',
        :'referral_id' => :'referralID',
        :'referral_value' => :'referralValue',
        :'rule_index' => :'ruleIndex',
        :'rule_name' => :'ruleName',
        :'condition_index' => :'conditionIndex',
        :'effect_index' => :'effectIndex',
        :'details' => :'details',
        :'evaluation_group_id' => :'evaluationGroupID',
        :'evaluation_group_mode' => :'evaluationGroupMode'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'campaign_id' => :'Integer',
        :'campaign_name' => :'String',
        :'ruleset_id' => :'Integer',
        :'coupon_id' => :'Integer',
        :'coupon_value' => :'String',
        :'referral_id' => :'Integer',
        :'referral_value' => :'String',
        :'rule_index' => :'Integer',
        :'rule_name' => :'String',
        :'condition_index' => :'Integer',
        :'effect_index' => :'Integer',
        :'details' => :'String',
        :'evaluation_group_id' => :'Integer',
        :'evaluation_group_mode' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::RuleFailureReason` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::RuleFailureReason`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'campaign_id')
        self.campaign_id = attributes[:'campaign_id']
      else
        self.campaign_id = nil
      end

      if attributes.key?(:'campaign_name')
        self.campaign_name = attributes[:'campaign_name']
      else
        self.campaign_name = nil
      end

      if attributes.key?(:'ruleset_id')
        self.ruleset_id = attributes[:'ruleset_id']
      else
        self.ruleset_id = nil
      end

      if attributes.key?(:'coupon_id')
        self.coupon_id = attributes[:'coupon_id']
      end

      if attributes.key?(:'coupon_value')
        self.coupon_value = attributes[:'coupon_value']
      end

      if attributes.key?(:'referral_id')
        self.referral_id = attributes[:'referral_id']
      end

      if attributes.key?(:'referral_value')
        self.referral_value = attributes[:'referral_value']
      end

      if attributes.key?(:'rule_index')
        self.rule_index = attributes[:'rule_index']
      else
        self.rule_index = nil
      end

      if attributes.key?(:'rule_name')
        self.rule_name = attributes[:'rule_name']
      else
        self.rule_name = nil
      end

      if attributes.key?(:'condition_index')
        self.condition_index = attributes[:'condition_index']
      end

      if attributes.key?(:'effect_index')
        self.effect_index = attributes[:'effect_index']
      end

      if attributes.key?(:'details')
        self.details = attributes[:'details']
      end

      if attributes.key?(:'evaluation_group_id')
        self.evaluation_group_id = attributes[:'evaluation_group_id']
      end

      if attributes.key?(:'evaluation_group_mode')
        self.evaluation_group_mode = attributes[:'evaluation_group_mode']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @campaign_id.nil?
        invalid_properties.push('invalid value for "campaign_id", campaign_id cannot be nil.')
      end

      if @campaign_name.nil?
        invalid_properties.push('invalid value for "campaign_name", campaign_name cannot be nil.')
      end

      if @ruleset_id.nil?
        invalid_properties.push('invalid value for "ruleset_id", ruleset_id cannot be nil.')
      end

      if @rule_index.nil?
        invalid_properties.push('invalid value for "rule_index", rule_index cannot be nil.')
      end

      if @rule_name.nil?
        invalid_properties.push('invalid value for "rule_name", rule_name cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @campaign_id.nil?
      return false if @campaign_name.nil?
      return false if @ruleset_id.nil?
      return false if @rule_index.nil?
      return false if @rule_name.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] campaign_id Value to be assigned
    def campaign_id=(campaign_id)
      if campaign_id.nil?
        fail ArgumentError, 'campaign_id cannot be nil'
      end

      @campaign_id = campaign_id
    end

    # Custom attribute writer method with validation
    # @param [Object] campaign_name Value to be assigned
    def campaign_name=(campaign_name)
      if campaign_name.nil?
        fail ArgumentError, 'campaign_name cannot be nil'
      end

      @campaign_name = campaign_name
    end

    # Custom attribute writer method with validation
    # @param [Object] ruleset_id Value to be assigned
    def ruleset_id=(ruleset_id)
      if ruleset_id.nil?
        fail ArgumentError, 'ruleset_id cannot be nil'
      end

      @ruleset_id = ruleset_id
    end

    # Custom attribute writer method with validation
    # @param [Object] rule_index Value to be assigned
    def rule_index=(rule_index)
      if rule_index.nil?
        fail ArgumentError, 'rule_index cannot be nil'
      end

      @rule_index = rule_index
    end

    # Custom attribute writer method with validation
    # @param [Object] rule_name Value to be assigned
    def rule_name=(rule_name)
      if rule_name.nil?
        fail ArgumentError, 'rule_name cannot be nil'
      end

      @rule_name = rule_name
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          campaign_id == o.campaign_id &&
          campaign_name == o.campaign_name &&
          ruleset_id == o.ruleset_id &&
          coupon_id == o.coupon_id &&
          coupon_value == o.coupon_value &&
          referral_id == o.referral_id &&
          referral_value == o.referral_value &&
          rule_index == o.rule_index &&
          rule_name == o.rule_name &&
          condition_index == o.condition_index &&
          effect_index == o.effect_index &&
          details == o.details &&
          evaluation_group_id == o.evaluation_group_id &&
          evaluation_group_mode == o.evaluation_group_mode
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [campaign_id, campaign_name, ruleset_id, coupon_id, coupon_value, referral_id, referral_value, rule_index, rule_name, condition_index, effect_index, details, evaluation_group_id, evaluation_group_mode].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
