=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module TalonOne
  # Ruleset in the V2 JSON block format.
  class RulesetV2 < ApiModelBase
    # Internal ID of this entity.
    attr_accessor :id

    # The time this entity was created.
    attr_accessor :created

    # The ID of the user that created this ruleset.
    attr_accessor :user_id

    # The ID of the campaign that owns this entity.
    attr_accessor :campaign_id

    # The ID of the campaign template that owns this entity.
    attr_accessor :template_id

    # Timestamp indicating when this ruleset was activated.
    attr_accessor :activated_at

    # Set of promotion rules.
    attr_accessor :promotion_rules

    # Set of strikethrough rules.
    attr_accessor :strikethrough_rules

    # Variable bindings of type selector.
    attr_accessor :selectors

    # Variable bindings of type bundle.
    attr_accessor :bundles

    # Variable bindings of type template parameter.
    attr_accessor :parameters

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'created' => :'created',
        :'user_id' => :'userId',
        :'campaign_id' => :'campaignId',
        :'template_id' => :'templateId',
        :'activated_at' => :'activatedAt',
        :'promotion_rules' => :'promotionRules',
        :'strikethrough_rules' => :'strikethroughRules',
        :'selectors' => :'selectors',
        :'bundles' => :'bundles',
        :'parameters' => :'parameters'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'created' => :'Time',
        :'user_id' => :'Integer',
        :'campaign_id' => :'Integer',
        :'template_id' => :'Integer',
        :'activated_at' => :'Time',
        :'promotion_rules' => :'Array<PromotionRuleV2>',
        :'strikethrough_rules' => :'Array<StrikethroughRuleV2>',
        :'selectors' => :'Array<Hash<String, Object>>',
        :'bundles' => :'Array<Hash<String, Object>>',
        :'parameters' => :'Array<Hash<String, Object>>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::RulesetV2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::RulesetV2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'created')
        self.created = attributes[:'created']
      else
        self.created = nil
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      else
        self.user_id = nil
      end

      if attributes.key?(:'campaign_id')
        self.campaign_id = attributes[:'campaign_id']
      end

      if attributes.key?(:'template_id')
        self.template_id = attributes[:'template_id']
      end

      if attributes.key?(:'activated_at')
        self.activated_at = attributes[:'activated_at']
      end

      if attributes.key?(:'promotion_rules')
        if (value = attributes[:'promotion_rules']).is_a?(Array)
          self.promotion_rules = value
        end
      else
        self.promotion_rules = nil
      end

      if attributes.key?(:'strikethrough_rules')
        if (value = attributes[:'strikethrough_rules']).is_a?(Array)
          self.strikethrough_rules = value
        end
      else
        self.strikethrough_rules = nil
      end

      if attributes.key?(:'selectors')
        if (value = attributes[:'selectors']).is_a?(Array)
          self.selectors = value
        end
      end

      if attributes.key?(:'bundles')
        if (value = attributes[:'bundles']).is_a?(Array)
          self.bundles = value
        end
      end

      if attributes.key?(:'parameters')
        if (value = attributes[:'parameters']).is_a?(Array)
          self.parameters = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @created.nil?
        invalid_properties.push('invalid value for "created", created cannot be nil.')
      end

      if @user_id.nil?
        invalid_properties.push('invalid value for "user_id", user_id cannot be nil.')
      end

      if @promotion_rules.nil?
        invalid_properties.push('invalid value for "promotion_rules", promotion_rules cannot be nil.')
      end

      if @strikethrough_rules.nil?
        invalid_properties.push('invalid value for "strikethrough_rules", strikethrough_rules cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @created.nil?
      return false if @user_id.nil?
      return false if @promotion_rules.nil?
      return false if @strikethrough_rules.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] created Value to be assigned
    def created=(created)
      if created.nil?
        fail ArgumentError, 'created cannot be nil'
      end

      @created = created
    end

    # Custom attribute writer method with validation
    # @param [Object] user_id Value to be assigned
    def user_id=(user_id)
      if user_id.nil?
        fail ArgumentError, 'user_id cannot be nil'
      end

      @user_id = user_id
    end

    # Custom attribute writer method with validation
    # @param [Object] promotion_rules Value to be assigned
    def promotion_rules=(promotion_rules)
      if promotion_rules.nil?
        fail ArgumentError, 'promotion_rules cannot be nil'
      end

      @promotion_rules = promotion_rules
    end

    # Custom attribute writer method with validation
    # @param [Object] strikethrough_rules Value to be assigned
    def strikethrough_rules=(strikethrough_rules)
      if strikethrough_rules.nil?
        fail ArgumentError, 'strikethrough_rules cannot be nil'
      end

      @strikethrough_rules = strikethrough_rules
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          created == o.created &&
          user_id == o.user_id &&
          campaign_id == o.campaign_id &&
          template_id == o.template_id &&
          activated_at == o.activated_at &&
          promotion_rules == o.promotion_rules &&
          strikethrough_rules == o.strikethrough_rules &&
          selectors == o.selectors &&
          bundles == o.bundles &&
          parameters == o.parameters
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, created, user_id, campaign_id, template_id, activated_at, promotion_rules, strikethrough_rules, selectors, bundles, parameters].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
