=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.24.0

=end

require 'date'
require 'time'

module TalonOne
  # This effect indicates that the customer's progress in an achievement was started during the current session. The progress value is set to 0. It is triggered when a rule using the [Start achievement progress](https://docs.talon.one/docs/product/rules/effects/use-effects#start-achievement-progress) effect is successfully validated.  This effect only marks the start of progress tracking. It can fire together with `increaseAchievementProgress` when progress starts and increases at the same time. In that case, both effects share the same `progressTrackerId`, `startDate`, and `endDate`.  For [on-completion achievements](https://docs.talon.one/docs/product/campaigns/achievements/achievements-overview#recurring-on-completion-achievements), each iteration also gets its own `startDate` and `endDate`. 
  class StartAchievementProgressEffectProps < ApiModelBase
    # The ID of the achievement.
    attr_accessor :achievement_id

    # The name of the achievement.
    attr_accessor :achievement_name

    # The ID of the customer's progress tracker for this achievement.  For [on-completion achievements](https://docs.talon.one/docs/product/campaigns/achievements/achievements-overview#recurring-on-completion-achievements), this effect generates a unique ID for each iteration.
    attr_accessor :progress_tracker_id

    # The target value to complete the achievement.
    attr_accessor :target

    # Timestamp at which the customer's progress started.
    attr_accessor :start_date

    # Timestamp at which this progress period ends.  Only returned for achievements that have a fixed end date. [On-completion achievements](https://docs.talon.one/docs/product/campaigns/achievements/achievements-overview#recurring-on-completion-achievements) have no end date.
    attr_accessor :end_date

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'achievement_id' => :'achievementId',
        :'achievement_name' => :'achievementName',
        :'progress_tracker_id' => :'progressTrackerId',
        :'target' => :'target',
        :'start_date' => :'startDate',
        :'end_date' => :'endDate'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'achievement_id' => :'Integer',
        :'achievement_name' => :'String',
        :'progress_tracker_id' => :'Integer',
        :'target' => :'Float',
        :'start_date' => :'Time',
        :'end_date' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::StartAchievementProgressEffectProps` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::StartAchievementProgressEffectProps`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'achievement_id')
        self.achievement_id = attributes[:'achievement_id']
      else
        self.achievement_id = nil
      end

      if attributes.key?(:'achievement_name')
        self.achievement_name = attributes[:'achievement_name']
      else
        self.achievement_name = nil
      end

      if attributes.key?(:'progress_tracker_id')
        self.progress_tracker_id = attributes[:'progress_tracker_id']
      else
        self.progress_tracker_id = nil
      end

      if attributes.key?(:'target')
        self.target = attributes[:'target']
      else
        self.target = nil
      end

      if attributes.key?(:'start_date')
        self.start_date = attributes[:'start_date']
      else
        self.start_date = nil
      end

      if attributes.key?(:'end_date')
        self.end_date = attributes[:'end_date']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @achievement_id.nil?
        invalid_properties.push('invalid value for "achievement_id", achievement_id cannot be nil.')
      end

      if @achievement_name.nil?
        invalid_properties.push('invalid value for "achievement_name", achievement_name cannot be nil.')
      end

      if @progress_tracker_id.nil?
        invalid_properties.push('invalid value for "progress_tracker_id", progress_tracker_id cannot be nil.')
      end

      if @target.nil?
        invalid_properties.push('invalid value for "target", target cannot be nil.')
      end

      if @start_date.nil?
        invalid_properties.push('invalid value for "start_date", start_date cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @achievement_id.nil?
      return false if @achievement_name.nil?
      return false if @progress_tracker_id.nil?
      return false if @target.nil?
      return false if @start_date.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] achievement_id Value to be assigned
    def achievement_id=(achievement_id)
      if achievement_id.nil?
        fail ArgumentError, 'achievement_id cannot be nil'
      end

      @achievement_id = achievement_id
    end

    # Custom attribute writer method with validation
    # @param [Object] achievement_name Value to be assigned
    def achievement_name=(achievement_name)
      if achievement_name.nil?
        fail ArgumentError, 'achievement_name cannot be nil'
      end

      @achievement_name = achievement_name
    end

    # Custom attribute writer method with validation
    # @param [Object] progress_tracker_id Value to be assigned
    def progress_tracker_id=(progress_tracker_id)
      if progress_tracker_id.nil?
        fail ArgumentError, 'progress_tracker_id cannot be nil'
      end

      @progress_tracker_id = progress_tracker_id
    end

    # Custom attribute writer method with validation
    # @param [Object] target Value to be assigned
    def target=(target)
      if target.nil?
        fail ArgumentError, 'target cannot be nil'
      end

      @target = target
    end

    # Custom attribute writer method with validation
    # @param [Object] start_date Value to be assigned
    def start_date=(start_date)
      if start_date.nil?
        fail ArgumentError, 'start_date cannot be nil'
      end

      @start_date = start_date
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          achievement_id == o.achievement_id &&
          achievement_name == o.achievement_name &&
          progress_tracker_id == o.progress_tracker_id &&
          target == o.target &&
          start_date == o.start_date &&
          end_date == o.end_date
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [achievement_id, achievement_name, progress_tracker_id, target, start_date, end_date].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
