=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) to integrate with our platform. - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment.  For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#tag/Customer-sessions/operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}`. 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.22.0

=end

require 'date'
require 'time'

module TalonOne
  class SupportRequestInput < ApiModelBase
    # Identifier of the Application connected to the loyalty program or the campaign. It is displayed in your Talon.One deployment URL.
    attr_accessor :application_id

    # Identifier of the campaign where the coupon or gift card is created.
    attr_accessor :campaign_id

    # Identifier of the loyalty program. You can get the ID with the [List loyalty programs](https://docs.talon.one/management-api#tag/Loyalty/operation/getLoyaltyPrograms) endpoint.
    attr_accessor :loyalty_program_id

    # Identifier of the subledger the points are added to or deducted from. If there is no existing subledger with this ID, the subledger is created automatically.
    attr_accessor :subledger_id

    # Integration ID of the customer profile linked to the support request.
    attr_accessor :customer_profile_id

    # Type of reward requested, including gift cards, personal coupons, and loyalty point additions or deductions.
    attr_accessor :request_type

    # Requested monetary balance of the gift card or the number of loyalty points to be added or deducted.
    attr_accessor :request_value

    # Notes attached to the support request.
    attr_accessor :request_note

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'application_id' => :'applicationId',
        :'campaign_id' => :'campaignId',
        :'loyalty_program_id' => :'loyaltyProgramId',
        :'subledger_id' => :'subledgerId',
        :'customer_profile_id' => :'customerProfileId',
        :'request_type' => :'requestType',
        :'request_value' => :'requestValue',
        :'request_note' => :'requestNote'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'application_id' => :'Integer',
        :'campaign_id' => :'Integer',
        :'loyalty_program_id' => :'Integer',
        :'subledger_id' => :'Integer',
        :'customer_profile_id' => :'String',
        :'request_type' => :'String',
        :'request_value' => :'Float',
        :'request_note' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::SupportRequestInput` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::SupportRequestInput`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'application_id')
        self.application_id = attributes[:'application_id']
      else
        self.application_id = nil
      end

      if attributes.key?(:'campaign_id')
        self.campaign_id = attributes[:'campaign_id']
      end

      if attributes.key?(:'loyalty_program_id')
        self.loyalty_program_id = attributes[:'loyalty_program_id']
      end

      if attributes.key?(:'subledger_id')
        self.subledger_id = attributes[:'subledger_id']
      end

      if attributes.key?(:'customer_profile_id')
        self.customer_profile_id = attributes[:'customer_profile_id']
      else
        self.customer_profile_id = nil
      end

      if attributes.key?(:'request_type')
        self.request_type = attributes[:'request_type']
      else
        self.request_type = nil
      end

      if attributes.key?(:'request_value')
        self.request_value = attributes[:'request_value']
      end

      if attributes.key?(:'request_note')
        self.request_note = attributes[:'request_note']
      else
        self.request_note = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @application_id.nil?
        invalid_properties.push('invalid value for "application_id", application_id cannot be nil.')
      end

      if @customer_profile_id.nil?
        invalid_properties.push('invalid value for "customer_profile_id", customer_profile_id cannot be nil.')
      end

      if @request_type.nil?
        invalid_properties.push('invalid value for "request_type", request_type cannot be nil.')
      end

      if !@request_value.nil? && @request_value <= 0
        invalid_properties.push('invalid value for "request_value", must be greater than 0.')
      end

      if @request_note.nil?
        invalid_properties.push('invalid value for "request_note", request_note cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @application_id.nil?
      return false if @customer_profile_id.nil?
      return false if @request_type.nil?
      request_type_validator = EnumAttributeValidator.new('String', ["gift_card", "personal_coupon", "loyalty_points_added", "loyalty_points_deducted"])
      return false unless request_type_validator.valid?(@request_type)
      return false if !@request_value.nil? && @request_value <= 0
      return false if @request_note.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] application_id Value to be assigned
    def application_id=(application_id)
      if application_id.nil?
        fail ArgumentError, 'application_id cannot be nil'
      end

      @application_id = application_id
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_profile_id Value to be assigned
    def customer_profile_id=(customer_profile_id)
      if customer_profile_id.nil?
        fail ArgumentError, 'customer_profile_id cannot be nil'
      end

      @customer_profile_id = customer_profile_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] request_type Object to be assigned
    def request_type=(request_type)
      validator = EnumAttributeValidator.new('String', ["gift_card", "personal_coupon", "loyalty_points_added", "loyalty_points_deducted"])
      unless validator.valid?(request_type)
        fail ArgumentError, "invalid value for \"request_type\", must be one of #{validator.allowable_values}."
      end
      @request_type = request_type
    end

    # Custom attribute writer method with validation
    # @param [Object] request_value Value to be assigned
    def request_value=(request_value)
      if request_value.nil?
        fail ArgumentError, 'request_value cannot be nil'
      end

      if request_value <= 0
        fail ArgumentError, 'invalid value for "request_value", must be greater than 0.'
      end

      @request_value = request_value
    end

    # Custom attribute writer method with validation
    # @param [Object] request_note Value to be assigned
    def request_note=(request_note)
      if request_note.nil?
        fail ArgumentError, 'request_note cannot be nil'
      end

      @request_note = request_note
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          application_id == o.application_id &&
          campaign_id == o.campaign_id &&
          loyalty_program_id == o.loyalty_program_id &&
          subledger_id == o.subledger_id &&
          customer_profile_id == o.customer_profile_id &&
          request_type == o.request_type &&
          request_value == o.request_value &&
          request_note == o.request_note
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [application_id, campaign_id, loyalty_program_id, subledger_id, customer_profile_id, request_type, request_value, request_note].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
