=begin
#Talon.One API

#Use the Talon.One API to integrate with your application and to manage applications and campaigns:  - Use the operations in the [Integration API section](#integration-api) are used to integrate with our platform - Use the operation in the [Management API section](#management-api) to manage applications and campaigns.  ## Determining the base URL of the endpoints  The API is available at the same hostname as your Campaign Manager deployment. For example, if you access the Campaign Manager at `https://yourbaseurl.talon.one/`, the URL for the [updateCustomerSessionV2](https://docs.talon.one/integration-api#operation/updateCustomerSessionV2) endpoint is `https://yourbaseurl.talon.one/v2/customer_sessions/{Id}` 

The version of the OpenAPI document: 

Generated by: https://openapi-generator.tech
Generator version: 7.19.0

=end

require 'date'
require 'time'

module TalonOne
  class TierDowngradeData < ApiModelBase
    # The integration ID of the customer profile whose tier was downgraded.
    attr_accessor :customer_profile_id

    # The ID of the loyalty program.
    attr_accessor :loyalty_program_id

    # The ID of the subledger, when applicable. If this field is empty, the main ledger is used.
    attr_accessor :subledger_id

    # The name of the customer's current tier.
    attr_accessor :current_tier

    # The number of points the customer had at the time of tier downgrade.
    attr_accessor :current_points

    # The name of the customer's previous tier.
    attr_accessor :old_tier

    # The exact date and time the tier expires.
    attr_accessor :tier_expiration_date

    # The exact date and time the tier was changed.
    attr_accessor :timestamp_of_tier_change

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'customer_profile_id' => :'CustomerProfileID',
        :'loyalty_program_id' => :'LoyaltyProgramID',
        :'subledger_id' => :'SubledgerID',
        :'current_tier' => :'CurrentTier',
        :'current_points' => :'CurrentPoints',
        :'old_tier' => :'OldTier',
        :'tier_expiration_date' => :'TierExpirationDate',
        :'timestamp_of_tier_change' => :'TimestampOfTierChange'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'customer_profile_id' => :'String',
        :'loyalty_program_id' => :'Integer',
        :'subledger_id' => :'String',
        :'current_tier' => :'String',
        :'current_points' => :'Float',
        :'old_tier' => :'String',
        :'tier_expiration_date' => :'Time',
        :'timestamp_of_tier_change' => :'Time'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `TalonOne::TierDowngradeData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `TalonOne::TierDowngradeData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'customer_profile_id')
        self.customer_profile_id = attributes[:'customer_profile_id']
      else
        self.customer_profile_id = nil
      end

      if attributes.key?(:'loyalty_program_id')
        self.loyalty_program_id = attributes[:'loyalty_program_id']
      else
        self.loyalty_program_id = nil
      end

      if attributes.key?(:'subledger_id')
        self.subledger_id = attributes[:'subledger_id']
      else
        self.subledger_id = ''
      end

      if attributes.key?(:'current_tier')
        self.current_tier = attributes[:'current_tier']
      end

      if attributes.key?(:'current_points')
        self.current_points = attributes[:'current_points']
      else
        self.current_points = nil
      end

      if attributes.key?(:'old_tier')
        self.old_tier = attributes[:'old_tier']
      else
        self.old_tier = nil
      end

      if attributes.key?(:'tier_expiration_date')
        self.tier_expiration_date = attributes[:'tier_expiration_date']
      end

      if attributes.key?(:'timestamp_of_tier_change')
        self.timestamp_of_tier_change = attributes[:'timestamp_of_tier_change']
      else
        self.timestamp_of_tier_change = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @customer_profile_id.nil?
        invalid_properties.push('invalid value for "customer_profile_id", customer_profile_id cannot be nil.')
      end

      if @loyalty_program_id.nil?
        invalid_properties.push('invalid value for "loyalty_program_id", loyalty_program_id cannot be nil.')
      end

      if @loyalty_program_id < 1
        invalid_properties.push('invalid value for "loyalty_program_id", must be greater than or equal to 1.')
      end

      if @subledger_id.nil?
        invalid_properties.push('invalid value for "subledger_id", subledger_id cannot be nil.')
      end

      if @current_points.nil?
        invalid_properties.push('invalid value for "current_points", current_points cannot be nil.')
      end

      if @old_tier.nil?
        invalid_properties.push('invalid value for "old_tier", old_tier cannot be nil.')
      end

      if @timestamp_of_tier_change.nil?
        invalid_properties.push('invalid value for "timestamp_of_tier_change", timestamp_of_tier_change cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @customer_profile_id.nil?
      return false if @loyalty_program_id.nil?
      return false if @loyalty_program_id < 1
      return false if @subledger_id.nil?
      return false if @current_points.nil?
      return false if @old_tier.nil?
      return false if @timestamp_of_tier_change.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] customer_profile_id Value to be assigned
    def customer_profile_id=(customer_profile_id)
      if customer_profile_id.nil?
        fail ArgumentError, 'customer_profile_id cannot be nil'
      end

      @customer_profile_id = customer_profile_id
    end

    # Custom attribute writer method with validation
    # @param [Object] loyalty_program_id Value to be assigned
    def loyalty_program_id=(loyalty_program_id)
      if loyalty_program_id.nil?
        fail ArgumentError, 'loyalty_program_id cannot be nil'
      end

      if loyalty_program_id < 1
        fail ArgumentError, 'invalid value for "loyalty_program_id", must be greater than or equal to 1.'
      end

      @loyalty_program_id = loyalty_program_id
    end

    # Custom attribute writer method with validation
    # @param [Object] subledger_id Value to be assigned
    def subledger_id=(subledger_id)
      if subledger_id.nil?
        fail ArgumentError, 'subledger_id cannot be nil'
      end

      @subledger_id = subledger_id
    end

    # Custom attribute writer method with validation
    # @param [Object] current_points Value to be assigned
    def current_points=(current_points)
      if current_points.nil?
        fail ArgumentError, 'current_points cannot be nil'
      end

      @current_points = current_points
    end

    # Custom attribute writer method with validation
    # @param [Object] old_tier Value to be assigned
    def old_tier=(old_tier)
      if old_tier.nil?
        fail ArgumentError, 'old_tier cannot be nil'
      end

      @old_tier = old_tier
    end

    # Custom attribute writer method with validation
    # @param [Object] timestamp_of_tier_change Value to be assigned
    def timestamp_of_tier_change=(timestamp_of_tier_change)
      if timestamp_of_tier_change.nil?
        fail ArgumentError, 'timestamp_of_tier_change cannot be nil'
      end

      @timestamp_of_tier_change = timestamp_of_tier_change
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          customer_profile_id == o.customer_profile_id &&
          loyalty_program_id == o.loyalty_program_id &&
          subledger_id == o.subledger_id &&
          current_tier == o.current_tier &&
          current_points == o.current_points &&
          old_tier == o.old_tier &&
          tier_expiration_date == o.tier_expiration_date &&
          timestamp_of_tier_change == o.timestamp_of_tier_change
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [customer_profile_id, loyalty_program_id, subledger_id, current_tier, current_points, old_tier, tier_expiration_date, timestamp_of_tier_change].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
